# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           mozlz4
Version:        0.1.0
Release:        %autorelease
Summary:        Decompress / compress mozlz4 files, with precompiled binaries for Windows and Linux.

SourceLicense:  MIT
# 0BSD OR MIT OR Apache-2.0
# Apache-2.0 OR MIT
# MIT
# MIT OR Apache-2.0
# MIT OR Zlib OR Apache-2.0
# Unlicense OR MIT  
License:        (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 OR MIT) AND (MIT OR Apache-2.0) AND (MIT OR Zlib OR Apache-2.0) AND (Unlicense OR MIT) AND MIT
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/jusw85/mozlz4
Source:         %{url}/archive/v%{version}/%{name}-v%{version}.tar.gz
# Manually created patch for downstream crate metadata changes
Patch:          mozlz4-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 26

## for mozlz4-sys build dependencies
BuildRequires: (crate(cc/default) >= 1.0.0 with crate(cc/default) < 2.0.0~)

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n mozlz4-%{version} -p1
%cargo_prep


%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
# FIXME: no license files detected
%license LICENSE.dependencies
%{_bindir}/mozlz4

%changelog
%autochangelog
