# Generated by rust2rpm 27
# * Disable tests because of missing test data (excluded in Cargo.toml by
#   upstream)
%bcond check 0

%global crate jj-cli

Name:           jujutsu
Version:        0.34.0
Release:        %autorelease
Summary:        Jujutsu - an experimental version control system

License:        Apache-2.0
URL:            https://crates.io/crates/jj-cli
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          jj-cli-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

# Requires git to clone repo, also it is required for testing
BuildRequires:  git-core
Requires:       git-core

## TODO add bash/fish/zsh completion
## in install run built-jj-bin util completion  *sh > dst file

%global _description %{expand:
Jujutsu - an experimental version control system.}

%description %{_description}

%files
%license LICENSE
%license docs/images/LICENSE
%license LICENSE.dependencies
%{_bindir}/jj

%package        -n rust-%{crate}-devel
Summary:        %{summary}
BuildArch:      noarch

%description    -n rust-%{crate}-devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          -n rust-%{crate}-devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/docs/images/LICENSE
%{crate_instdir}/

%package     -n rust-%{crate}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{crate}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n rust-%{crate}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{crate}+bench-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{crate}+bench-devel %{_description}

This package contains library source intended for building other packages which
use the "bench" feature of the "%{crate}" crate.

%files       -n rust-%{crate}+bench-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{crate}+git-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{crate}+git-devel %{_description}

This package contains library source intended for building other packages which
use the "git" feature of the "%{crate}" crate.

%files       -n rust-%{crate}+git-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{crate}+test-fakes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{crate}+test-fakes-devel %{_description}

This package contains library source intended for building other packages which
use the "test-fakes" feature of the "%{crate}" crate.

%files       -n rust-%{crate}+test-fakes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{crate}+watchman-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{crate}+watchman-devel %{_description}

This package contains library source intended for building other packages which
use the "watchman" feature of the "%{crate}" crate.

%files       -n rust-%{crate}+watchman-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
