# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/mattn/efm-langserver
%global goipath         github.com/mattn/efm-langserver
Version:                0.0.54

%gometa -L -f


Name:           efm-langserver
Release:        %autorelease
Summary:        General purpose Language Server

# Generated by go-vendor-tools
License:        Apache-2.0 AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
General purpose Language Server.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/efm-langserver %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md schema.md
%{_bindir}/efm-langserver


%changelog
%autochangelog
