# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate rmux-sdk

Name:           rust-rmux-sdk
Version:        0.3.1
Release:        %autorelease
Summary:        Public, daemon-backed Rust SDK for the RMUX terminal multiplexer

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/rmux-sdk
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          rmux-sdk-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli

%global _description %{expand:
Public, daemon-backed Rust SDK for the RMUX terminal multiplexer
(facade, ensure-session, snapshots, events, detach helpers).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+crossterm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crossterm-devel %{_description}

This package contains library source intended for building other packages which
use the "crossterm" feature of the "%{crate}" crate.

%files       -n %{name}+crossterm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+regex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regex-devel %{_description}

This package contains library source intended for building other packages which
use the "regex" feature of the "%{crate}" crate.

%files       -n %{name}+regex-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
# Drop tests that require CARGO_BIN_EXE_rmux env set to the built `rmux` binary path
# otherwise it will try to build one, and will definitely failed due to no workspace/Cargo.toml
tomcli-set Cargo.toml arrays delitem test --key name 'layout_builder'
tomcli-set Cargo.toml arrays delitem test --key name 'lifecycle'
tomcli-set Cargo.toml arrays delitem test --key name 'pane_input'
tomcli-set Cargo.toml arrays delitem test --key name 'pane_queries'
tomcli-set Cargo.toml arrays delitem test --key name 'pane_set'
tomcli-set Cargo.toml arrays delitem test --key name 'session'
tomcli-set Cargo.toml arrays delitem test --key name 'smoke_v1'
tomcli-set Cargo.toml arrays delitem test --key name 'smoke_v1_full'
tomcli-set Cargo.toml arrays delitem test --key name 'terminal_automation'
tomcli-set Cargo.toml arrays delitem test --key name 'window'
# Drop feature which is used for windows
tomcli-set Cargo.toml arrays delitem dev-dependencies.crossterm.features 'windows'
tomcli-set Cargo.toml arrays delitem dependencies.crossterm.features 'windows'
# cargo2rpm bug, see https://codeberg.org/rust2rpm/cargo2rpm/issues/26
tomcli-set Cargo.toml append 'target."cfg(unix)".dependencies.tokio.features' `tomcli-get -F newline-list Cargo.toml dependencies.tokio.features`
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip tests that require CARGO_BIN_EXE_rmux env set to the built `rmux`
#   binary path
# * skip tests that require original Cargo.toml
%{cargo_test -- -- --exact %{shrink:
    --skip live_wait_for_next_ignores_history_and_matches_split_future_output
    --skip wait_for_text_observes_rendered_daemon_output
    --skip rmux_sdk_cargo_manifest_does_not_depend_on_internal_crates
    --skip rmux_sdk_cargo_manifest_does_not_redeclare_proto_in_dev_dependencies
    --skip rmux_sdk_tokio_dependency_stays_narrow_async_io_plumbing
}}
%endif

%changelog
%autochangelog
