# Generated by go2rpm 1.17.1
%bcond check 1
%bcond bootstrap 1

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/zricethezav/gitleaks
%global goipath         github.com/zricethezav/gitleaks
Version:                8.28.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global goaltipaths     github.com/zricethezav/gitleaks/v8

%global common_description %{expand:
Find secrets with Gitleaks 🔑.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md USERS.md\\\
                        cmd/generate/config/rules/readme.go\\\
                        report_templates/README.md

Name:           golang-github-zricethezav-gitleaks
Release:        %autorelease
Summary:        Find secrets with Gitleaks 🔑

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/gitleaks %{goipath}
%endif

%global gosupfiles config/gitleaks.toml
%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc CONTRIBUTING.md README.md USERS.md cmd/generate/config/rules/readme.go
%doc report_templates/README.md
%{_bindir}/gitleaks
%endif

%gopkgfiles

%changelog
%autochangelog
