# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate minidump

Name:           rust-minidump
Version:        0.26.1
Release:        %autorelease
Summary:        Parser for the minidump format

License:        MIT
URL:            https://crates.io/crates/minidump
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          minidump-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A parser for the minidump format.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary_impls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary_impls-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary_impls" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary_impls-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --skip "minidump::Minidump<'a,T>::get_stream" --skip src/lib.rs
%endif

%changelog
%autochangelog
