# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate sapling-streampager

Name:           rust-sapling-streampager
Version:        0.11.0
Release:        %autorelease
Summary:        Streampager is a pager for command output or large files

License:        MIT
URL:            https://crates.io/crates/sapling-streampager
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          sapling-streampager-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Streampager is a pager for command output or large files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+keymap-file-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+keymap-file-devel %{_description}

This package contains library source intended for building other packages which
use the "keymap-file" feature of the "%{crate}" crate.

%files       -n %{name}+keymap-file-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+load_file-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+load_file-devel %{_description}

This package contains library source intended for building other packages which
use the "load_file" feature of the "%{crate}" crate.

%files       -n %{name}+load_file-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+notify-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+notify-devel %{_description}

This package contains library source intended for building other packages which
use the "notify" feature of the "%{crate}" crate.

%files       -n %{name}+notify-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
