# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate const-hex

Name:           rust-const-hex
Version:        1.19.0
Release:        %autorelease
Summary:        Fast byte array to hex string conversion

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/const-hex
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          const-hex-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fast byte array to hex string conversion.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+__fuzzing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+__fuzzing-devel %{_description}

This package contains library source intended for building other packages which
use the "__fuzzing" feature of the "%{crate}" crate.

%files       -n %{name}+__fuzzing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+core-error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+core-error-devel %{_description}

This package contains library source intended for building other packages which
use the "core-error" feature of the "%{crate}" crate.

%files       -n %{name}+core-error-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+force-generic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+force-generic-devel %{_description}

This package contains library source intended for building other packages which
use the "force-generic" feature of the "%{crate}" crate.

%files       -n %{name}+force-generic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hex-devel %{_description}

This package contains library source intended for building other packages which
use the "hex" feature of the "%{crate}" crate.

%files       -n %{name}+hex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly" feature of the "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+portable-simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+portable-simd-devel %{_description}

This package contains library source intended for building other packages which
use the "portable-simd" feature of the "%{crate}" crate.

%files       -n %{name}+portable-simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
