# Generated by rust2rpm 28
%bcond check 1

%global crate apk-info-cli

Name:           rust-apk-info-cli
Version:        1.0.11
Release:        %autorelease
Summary:        Command-line tool to inspect and extract APK files

License:        Apache-2.0
URL:            https://crates.io/crates/apk-info-cli
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A command-line tool to inspect and extract APK files.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/apk-info

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
