# Generated by go2rpm 1.17.1
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/dustin/gojson
%global goipath         github.com/dustin/gojson
%global commit          2e71ec9dd5adce3b168cd0dbde03b5cc04951c30

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Fork of go's encoding/json with the scanner API made public.}

%global golicenses      LICENSE
Name:           golang-github-dustin-gojson
Version:        0
Release:        %autorelease -p
Summary:        Fork of go's encoding/json with the scanner API made public

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%global gotestflags -vet=off %{gotestflags}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
