# Generated by rust2rpm 28
%bcond check 1

%global crate rmux

Name:           rust-rmux
Version:        0.3.0
Release:        %autorelease
Summary:        Local terminal multiplexer with a tmux-style CLI, daemon runtime, Rust SDK, and ratatui integration

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/rmux
Source:         %{crates_source}
# * include document files for config
Source2:        https://raw.githubusercontent.com/Helvesec/rmux/refs/tags/v%{version}/docs/human-friendly-config.md
# * include document files for config
Source3:        https://raw.githubusercontent.com/Helvesec/rmux/refs/tags/v%{version}/docs/examples/human-friendly.conf
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          rmux-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli
%if %{with check}
BuildRequires:  man
%endif

%global _description %{expand:
A local terminal multiplexer with a tmux-style CLI, daemon runtime, Rust
SDK, and ratatui integration.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# (MIT OR Apache-2.0) AND Unicode-DFS-2016
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# MIT
# MIT OR Apache-2.0
# Unlicense OR MIT
License:        MIT AND Unicode-DFS-2016
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%doc README.md
%doc human-friendly-config.md
%doc human-friendly.conf
%{_bindir}/rmux
%{_mandir}/man1/rmux.1*

%prep
%autosetup -n %{crate}-%{version} -p1
# Remove build dependencies and script for windows
tomcli-set Cargo.toml del package.build
tomcli-set Cargo.toml del build-dependencies.embed-manifest
rm build.rs
# Ease clap version restriction
tomcli-set Cargo.toml str dependencies.clap.version `tomcli-get Cargo.toml dependencies.clap.version | tr  -d =`
# Restrict rmux-* dependencies version to exact match
tomcli-set Cargo.toml str dependencies.rmux-client.version =`tomcli-get Cargo.toml dependencies.rmux-client.version`
tomcli-set Cargo.toml str dependencies.rmux-core.version =`tomcli-get Cargo.toml dependencies.rmux-core.version`
tomcli-set Cargo.toml str dependencies.rmux-os.version =`tomcli-get Cargo.toml dependencies.rmux-os.version`
tomcli-set Cargo.toml str dependencies.rmux-proto.version =`tomcli-get Cargo.toml dependencies.rmux-proto.version`
tomcli-set Cargo.toml str dependencies.rmux-server.version =`tomcli-get Cargo.toml dependencies.rmux-server.version`
tomcli-set Cargo.toml str dev-dependencies.rmux-core.version =`tomcli-get Cargo.toml dev-dependencies.rmux-core.version`
tomcli-set Cargo.toml str dev-dependencies.rmux-proto.version =`tomcli-get Cargo.toml dev-dependencies.rmux-proto.version`
tomcli-set Cargo.toml str dev-dependencies.rmux-pty.version =`tomcli-get Cargo.toml dev-dependencies.rmux-pty.version`
tomcli-set Cargo.toml str dev-dependencies.rmux-sdk.version =`tomcli-get Cargo.toml dev-dependencies.rmux-sdk.version`
%cargo_prep
# copy in document files
cp -p %{SOURCE2} .
cp -p %{SOURCE3} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dpm0644 -t %{buildroot}%{_mandir}/man1 rmux.1

%if %{with check}
%check
# * skip tests that require debug_assertions to use BINARY_OVERRIDE_ENV to call
#   rmux-launcher.sh for test
%{cargo_test -- -- --exact %{shrink:
    --skip rapid_create_kill_churn_reaps_children_without_socket_leaks
    --skip attach_session_is_a_start_server_command
    --skip command_free_invocation_auto_starts_default_new_session
    --skip sanitized_session_names_allow_new_session_auto_start
    --skip shell_command_starts_the_server_and_returns_the_shell_exit_status
    --skip start_server_is_a_start_server_command
    --skip ensure_server_running_reexecs_the_hidden_rmux_daemon
    --skip multi_pane_kill_reaps_children_under_the_hidden_daemon
    --skip session_name_rewrites_preserve_server_state
    --skip canonical_session_workflow_runs_end_to_end
}}
%endif

%changelog
%autochangelog
