Name:           lz4json
Version:        2
Release:        %autorelease
Summary:        C decompress tool for mozilla lz4json format 

License:        BSD-2-ish
URL:            https://github.com/andikleen/lz4json
Source0:        %{url}/archive/v%{version}/%{name}-v%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  make
#BuildRequires:  lz4-devel
BuildRequires:  pkgconfig(liblz4)

%global _binname %{name}cat

%description %{expand:
little utility to unpack lz4json files as generated by Firefox's bookmark backups and session restore.
This is a different format from what the normal lz4 utility expects.
The data is dumped to stdout.
}


%prep
%autosetup


%build
%make_build CFLAGS="$CFLAGS"


%install
install -Dpm0755 -t %{buildroot}%{_bindir} %{_binname}
install -Dpm0644 -t %{buildroot}%{_mandir}/man1 %{_binname}.1

%check


%files
%license
%doc README
%{_mandir}/man1/%{_binname}.1*
%{_bindir}/%{_binname}


%changelog
%autochangelog

