# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate cachemap2

Name:           rust-cachemap2
Version:        0.3.0
Release:        %autorelease
Summary:        Concurrent insert-only hashmap for caching values

License:        MIT
URL:            https://crates.io/crates/cachemap2
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A concurrent insert-only hashmap for caching values.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/ChangeLog.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi_stable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi_stable-devel %{_description}

This package contains library source intended for building other packages which
use the "abi_stable" feature of the "%{crate}" crate.

%files       -n %{name}+abi_stable-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dashmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dashmap-devel %{_description}

This package contains library source intended for building other packages which
use the "dashmap" feature of the "%{crate}" crate.

%files       -n %{name}+dashmap-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
