# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate breakpad-symbols

Name:           rust-breakpad-symbols
Version:        0.26.1
Release:        %autorelease
Summary:        Library for working with Google Breakpad's text-format symbol files

License:        MIT
URL:            https://crates.io/crates/breakpad-symbols
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library for working with Google Breakpad's text-format symbol files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cab-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cab-devel %{_description}

This package contains library source intended for building other packages which
use the "cab" feature of the "%{crate}" crate.

%files       -n %{name}+cab-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fuzz-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fuzz-devel %{_description}

This package contains library source intended for building other packages which
use the "fuzz" feature of the "%{crate}" crate.

%files       -n %{name}+fuzz-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http-devel %{_description}

This package contains library source intended for building other packages which
use the "http" feature of the "%{crate}" crate.

%files       -n %{name}+http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mozilla_cab_symbols-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mozilla_cab_symbols-devel %{_description}

This package contains library source intended for building other packages which
use the "mozilla_cab_symbols" feature of the "%{crate}" crate.

%files       -n %{name}+mozilla_cab_symbols-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+reqwest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+reqwest-devel %{_description}

This package contains library source intended for building other packages which
use the "reqwest" feature of the "%{crate}" crate.

%files       -n %{name}+reqwest-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tempfile-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tempfile-devel %{_description}

This package contains library source intended for building other packages which
use the "tempfile" feature of the "%{crate}" crate.

%files       -n %{name}+tempfile-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --skip "sym_file::test::test_symbolfile_from_crlf_file"  --skip "sym_file::test::test_symbolfile_from_lf_file" --skip "src/lib.rs"
%endif

%changelog
%autochangelog
