# Generated by rust2rpm 27
# * construct dependency fast
%bcond check 0
%global debug_package %{nil}

%global crate sourcemap

Name:           rust-sourcemap
Version:        8.0.1
Release:        %autorelease
Summary:        Basic sourcemap handling for Rust

License:        BSD-3-Clause
URL:            https://crates.io/crates/sourcemap
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          sourcemap-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Basic sourcemap handling for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ram_bundle-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ram_bundle-devel %{_description}

This package contains library source intended for building other packages which
use the "ram_bundle" feature of the "%{crate}" crate.

%files       -n %{name}+ram_bundle-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+scroll-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+scroll-devel %{_description}

This package contains library source intended for building other packages which
use the "scroll" feature of the "%{crate}" crate.

%files       -n %{name}+scroll-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
