# Generated by rust2rpm 27
# * Disable tests because of missing criterion
%bcond check 0
%global debug_package %{nil}

%global crate jj-lib

Name:           rust-jj-lib
Version:        0.32.0
Release:        %autorelease
Summary:        Library for Jujutsu - an experimental version control system

License:        Apache-2.0
URL:            https://crates.io/crates/jj-lib
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          jj-lib-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for Jujutsu - an experimental version control system.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+git-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+git-devel %{_description}

This package contains library source intended for building other packages which
use the "git" feature of the "%{crate}" crate.

%files       -n %{name}+git-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+testing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+testing-devel %{_description}

This package contains library source intended for building other packages which
use the "testing" feature of the "%{crate}" crate.

%files       -n %{name}+testing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+watchman-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+watchman-devel %{_description}

This package contains library source intended for building other packages which
use the "watchman" feature of the "%{crate}" crate.

%files       -n %{name}+watchman-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
