# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate serde_bser

Name:           rust-serde_bser
Version:        0.4.0
Release:        %autorelease
Summary:        Implements the Watchman BSER encoding for serde

License:        MIT
URL:            https://crates.io/crates/serde_bser
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Implements the Watchman BSER encoding for serde.
https://facebook.github.io/watchman/docs/bser.html.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug_bytes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug_bytes-devel %{_description}

This package contains library source intended for building other packages which
use the "debug_bytes" feature of the "%{crate}" crate.

%files       -n %{name}+debug_bytes-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
