# Generated by go2rpm 1.17.1
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}

# These lines will cause other go dependencies not installed if have a explict BuildRequires for a go package.
#%if %{with bootstrap}
#%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
#%endif

# https://github.com/gopasspw/gopass
%global goipath         github.com/gopasspw/gopass
Version:                1.15.16

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
The slightly more awesome standard unix password manager for teams.}

%global golicenses      LICENSE
%global godocs          docs ARCHITECTURE.md CHANGELOG.md CONTRIBUTING.md\\\
                        GOVERNANCE.md README.md

Name:           golang-github-gopasspw-gopass
Release:        %autorelease
Summary:        The slightly more awesome standard unix password manager for teams

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

#For test see: https://src.fedoraproject.org/rpms/gopass/blob/rawhide/f/gopass.spec
BuildRequires:  git-core
BuildRequires:  gnupg2
BuildRequires:  golang(github.com/gopasspw/gopass-hibp/pkg/hibp/api)
# This is required by gopass-hibp
BuildRequires:  golang(github.com/kjk/lzmadec)

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1
## failed test caused by github.com/schollz/closestmatch version mismatch
rm internal/action/find_test.go

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif


%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
git config --global user.email "%{name}-owner@fedoraproject.org"
git config --global user.name "%{name} maintainer"
%gocheck -d github.com/gopasspw/gopass/internal/config -d github.com/gopasspw/gopass/internal/store/leaf -d github.com/gopasspw/gopass/internal/updater -d github.com/gopasspw/gopass/pkg/fsutil -d helpers/postrel
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
