# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate libsql-ffi

Name:           rust-libsql-ffi
Version:        0.9.30
Release:        %autorelease
Summary:        Native bindings to libSQL

License:        MIT
URL:            https://crates.io/crates/libsql-ffi
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          libsql-ffi-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Native bindings to libSQL.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/bundled/SQLite3MultipleCiphers/LICENSE
%license %{crate_instdir}/bundled/SQLite3MultipleCiphers/LICENSE.spdx
%license %{crate_instdir}/bundled/sqlean/regexp/pcre2/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bundled-sqlcipher-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bundled-sqlcipher-devel %{_description}

This package contains library source intended for building other packages which
use the "bundled-sqlcipher" feature of the "%{crate}" crate.

%files       -n %{name}+bundled-sqlcipher-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bundled-sqlcipher-vendored-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bundled-sqlcipher-vendored-openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "bundled-sqlcipher-vendored-openssl" feature of the "%{crate}" crate.

%files       -n %{name}+bundled-sqlcipher-vendored-openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libsql-checkpoint-only-full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libsql-checkpoint-only-full-devel %{_description}

This package contains library source intended for building other packages which
use the "libsql-checkpoint-only-full" feature of the "%{crate}" crate.

%files       -n %{name}+libsql-checkpoint-only-full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libsql-disable-checkpoint-downgrade-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libsql-disable-checkpoint-downgrade-devel %{_description}

This package contains library source intended for building other packages which
use the "libsql-disable-checkpoint-downgrade" feature of the "%{crate}" crate.

%files       -n %{name}+libsql-disable-checkpoint-downgrade-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+multiple-ciphers-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multiple-ciphers-devel %{_description}

This package contains library source intended for building other packages which
use the "multiple-ciphers" feature of the "%{crate}" crate.

%files       -n %{name}+multiple-ciphers-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+preupdate_hook-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+preupdate_hook-devel %{_description}

This package contains library source intended for building other packages which
use the "preupdate_hook" feature of the "%{crate}" crate.

%files       -n %{name}+preupdate_hook-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+session-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+session-devel %{_description}

This package contains library source intended for building other packages which
use the "session" feature of the "%{crate}" crate.

%files       -n %{name}+session-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlcipher-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlcipher-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlcipher" feature of the "%{crate}" crate.

%files       -n %{name}+sqlcipher-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-crypto-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-crypto-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-crypto" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-crypto-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-fuzzy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-fuzzy-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-fuzzy" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-fuzzy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-math-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-math-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-math" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-math-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-regexp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-regexp-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-regexp" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-regexp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-stats-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-stats-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-stats" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-stats-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-text-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-text-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-text" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-text-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-uuid" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extensions-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extensions-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extensions" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extensions-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unlock_notify-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unlock_notify-devel %{_description}

This package contains library source intended for building other packages which
use the "unlock_notify" feature of the "%{crate}" crate.

%files       -n %{name}+unlock_notify-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasm32-wasi-vfs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm32-wasi-vfs-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm32-wasi-vfs" feature of the "%{crate}" crate.

%files       -n %{name}+wasm32-wasi-vfs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasmtime-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasmtime-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "wasmtime-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+wasmtime-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-asan-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-asan-devel %{_description}

This package contains library source intended for building other packages which
use the "with-asan" feature of the "%{crate}" crate.

%files       -n %{name}+with-asan-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
