# Generated by rust2rpm 28
%bcond check 1

%global crate sandlock-cli

Name:           rust-sandlock-cli
Version:        0.8.1
Release:        %autorelease
Summary:        CLI for sandlock process sandbox

License:        Apache-2.0
URL:            https://crates.io/crates/sandlock-cli
Source:         %{crates_source}
# * include license file
# * TODO https://github.com/multikernel/sandlock/pull/XX
Source2:        https://raw.githubusercontent.com/multikernel/sandlock/refs/tags/v%{version}/LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
CLI for sandlock process sandbox.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/sandlock

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# copy in license file
cp -p %{SOURCE2} .


%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
