# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate minidump-processor

Name:           rust-minidump-processor
Version:        0.26.1
Release:        %autorelease
Summary:        Library for producing stack traces and other useful information from minidump files

License:        MIT
URL:            https://crates.io/crates/minidump-processor
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          minidump-processor-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library for producing stack traces and other useful information from
minidump files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/json-schema.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debuginfo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debuginfo-devel %{_description}

This package contains library source intended for building other packages which
use the "debuginfo" feature of the "%{crate}" crate.

%files       -n %{name}+debuginfo-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+disasm_amd64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+disasm_amd64-devel %{_description}

This package contains library source intended for building other packages which
use the "disasm_amd64" feature of the "%{crate}" crate.

%files       -n %{name}+disasm_amd64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http-devel %{_description}

This package contains library source intended for building other packages which
use the "http" feature of the "%{crate}" crate.

%files       -n %{name}+http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mozilla_cab_symbols-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mozilla_cab_symbols-devel %{_description}

This package contains library source intended for building other packages which
use the "mozilla_cab_symbols" feature of the "%{crate}" crate.

%files       -n %{name}+mozilla_cab_symbols-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+yaxpeax-x86-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+yaxpeax-x86-devel %{_description}

This package contains library source intended for building other packages which
use the "yaxpeax-x86" feature of the "%{crate}" crate.

%files       -n %{name}+yaxpeax-x86-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --skip processor::process_minidump --skip test_processor_symbols --skip test_processor
%endif

%changelog
%autochangelog
