# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate samply-api

Name:           rust-samply-api
Version:        0.24.0
Release:        %autorelease
Summary:        JSON API for querying symbol information, uses samply-symbols

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/samply-api
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
JSON API for querying symbol information, uses samply-symbols.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+send_futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+send_futures-devel %{_description}

This package contains library source intended for building other packages which
use the "send_futures" feature of the "%{crate}" crate.

%files       -n %{name}+send_futures-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- \
--skip    android32_v5_local \
--skip    asm_with_continue \
--skip    asm_x86_64 \
--skip    stripped_macos \
--skip    win64_ci_v5_snapshot \
--skip    win64_local_v5_snapshot_1 \
--skip    win_exe


%endif

%changelog
%autochangelog
