archful = true
archive_name = "sandlock-0.7.0.tar.gz"
extras = [
    "mcp",
    "mcp-remote",
]
license = "Apache-2.0"
license_files_present = false
name = "sandlock"
python_name = "python-sandlock"
source = "PyPI"
summary = "Lightweight process sandbox using Landlock, seccomp, and seccomp user notification"
url = "https://github.com/multikernel/sandlock"
version = "0.7.0"
