# Generated by go2rpm 1.17.1
%bcond check 1

# https://github.com/gliderlabs/sigil
%global goipath         github.com/gliderlabs/sigil
Version:                0.11.5

%gometa -L -f


Name:           golang-github-gliderlabs-sigil
Release:        %autorelease
Summary:        Standalone string interpolator and template processor

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Standalone string interpolator and template processor.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
## NOTE: since `cmd/sigil` is not a folder, don't use the template one.
## NOTE: there're already a binary `sigil` for https://github.com/Sigil-Ebook/Sigil, so we change the binary name.
%gobuild -o %{gobuilddir}/bin/sigil-go %{goipath}/cmd/

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/sigil-go %{buildroot}%{_bindir}/sigil-go

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%{_bindir}/sigil-go


%changelog
%autochangelog
