# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate grammers-mtsender

Name:           rust-grammers-mtsender
Version:        0.9.0
Release:        %autorelease
Summary:        Sender implementation using the Mobile Transport Protocol

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/grammers-mtsender
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          grammers-mtsender-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A sender implementation using the Mobile Transport Protocol.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/DEPS.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-http-proxy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-http-proxy-devel %{_description}

This package contains library source intended for building other packages which
use the "async-http-proxy" feature of the "%{crate}" crate.

%files       -n %{name}+async-http-proxy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hickory-resolver-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hickory-resolver-devel %{_description}

This package contains library source intended for building other packages which
use the "hickory-resolver" feature of the "%{crate}" crate.

%files       -n %{name}+hickory-resolver-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+proxy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+proxy-devel %{_description}

This package contains library source intended for building other packages which
use the "proxy" feature of the "%{crate}" crate.

%files       -n %{name}+proxy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-socks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-socks-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-socks" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-socks-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+url-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+url-devel %{_description}

This package contains library source intended for building other packages which
use the "url" feature of the "%{crate}" crate.

%files       -n %{name}+url-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
