# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate inplace-vec-builder

Name:           rust-inplace-vec-builder
Version:        0.1.1
Release:        %autorelease
Summary:        Build a vec from a vec, in place

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/inplace-vec-builder
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Build a vec from a vec, in place.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+smallvec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+smallvec-devel %{_description}

This package contains library source intended for building other packages which
use the "smallvec" feature of the "%{crate}" crate.

%files       -n %{name}+smallvec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stdvec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stdvec-devel %{_description}

This package contains library source intended for building other packages which
use the "stdvec" feature of the "%{crate}" crate.

%files       -n %{name}+stdvec-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --skip src/lib.rs
%endif

%changelog
%autochangelog
