# Generated by rust2rpm 27
# * Disable tests because of missing test data (excluded in Cargo.toml by
#   upstream)
%bcond check 0
%global debug_package %{nil}

%global crate wsl

Name:           rust-wsl
Version:        0.1.0
Release:        %autorelease
Summary:        Detect if the program is running under Windows Subsystem for Linux

License:        MIT
URL:            https://crates.io/crates/wsl
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Detect if the program is running under Windows Subsystem for Linux.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
