# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate samply-symbols

Name:           rust-samply-symbols
Version:        0.24.1
Release:        %autorelease
Summary:        Symbolication utilities for the Firefox profiler

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/samply-symbols
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Symbolication utilities for the Firefox profiler.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bitvec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bitvec-devel %{_description}

This package contains library source intended for building other packages which
use the "bitvec" feature of the "%{crate}" crate.

%files       -n %{name}+bitvec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytesize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytesize-devel %{_description}

This package contains library source intended for building other packages which
use the "bytesize" feature of the "%{crate}" crate.

%files       -n %{name}+bytesize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+partial_read_stats-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+partial_read_stats-devel %{_description}

This package contains library source intended for building other packages which
use the "partial_read_stats" feature of the "%{crate}" crate.

%files       -n %{name}+partial_read_stats-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+send_futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+send_futures-devel %{_description}

This package contains library source intended for building other packages which
use the "send_futures" feature of the "%{crate}" crate.

%files       -n %{name}+send_futures-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- \
--skip    compare_snapshot \
--skip    example_linux \
--skip    example_linux_fallback \
--skip    fat_arch_1 \
--skip    fat_arch_2 \
--skip    linux_nonzero_base_address \
--skip    successful_dll \
--skip    successful_pdb \
--skip    successful_pdb2 \
--skip    successful_pdb_unspecified_id \
--skip    unspecified_id_fat_arch \
--skip    unsuccessful_pdb_wrong_id
%endif

%changelog
%autochangelog
