# Generated by rust2rpm 28
## disable tests due to removed features
%bcond check 0
%global debug_package %{nil}

%global crate libsql

Name:           rust-libsql
Version:        0.9.30
Release:        %autorelease
Summary:        LibSQL database library

License:        MIT
URL:            https://crates.io/crates/libsql
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          libsql-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The libSQL database library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/DEVELOPING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+anyhow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+anyhow-devel %{_description}

This package contains library source intended for building other packages which
use the "anyhow" feature of the "%{crate}" crate.

%files       -n %{name}+anyhow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bincode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bincode-devel %{_description}

This package contains library source intended for building other packages which
use the "bincode" feature of the "%{crate}" crate.

%files       -n %{name}+bincode-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cloudflare-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cloudflare-devel %{_description}

This package contains library source intended for building other packages which
use the "cloudflare" feature of the "%{crate}" crate.

%files       -n %{name}+cloudflare-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+core-devel %{_description}

This package contains library source intended for building other packages which
use the "core" feature of the "%{crate}" crate.

%files       -n %{name}+core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+crc32fast-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crc32fast-devel %{_description}

This package contains library source intended for building other packages which
use the "crc32fast" feature of the "%{crate}" crate.

%files       -n %{name}+crc32fast-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encryption-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encryption-devel %{_description}

This package contains library source intended for building other packages which
use the "encryption" feature of the "%{crate}" crate.

%files       -n %{name}+encryption-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hrana-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hrana-devel %{_description}

This package contains library source intended for building other packages which
use the "hrana" feature of the "%{crate}" crate.

%files       -n %{name}+hrana-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http-devel %{_description}

This package contains library source intended for building other packages which
use the "http" feature of the "%{crate}" crate.

%files       -n %{name}+http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libsql-sys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libsql-sys-devel %{_description}

This package contains library source intended for building other packages which
use the "libsql-sys" feature of the "%{crate}" crate.

%files       -n %{name}+libsql-sys-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libsql_replication-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libsql_replication-devel %{_description}

This package contains library source intended for building other packages which
use the "libsql_replication" feature of the "%{crate}" crate.

%files       -n %{name}+libsql_replication-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parser-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parser-devel %{_description}

This package contains library source intended for building other packages which
use the "parser" feature of the "%{crate}" crate.

%files       -n %{name}+parser-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stream-devel %{_description}

This package contains library source intended for building other packages which
use the "stream" feature of the "%{crate}" crate.

%files       -n %{name}+stream-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tls" feature of the "%{crate}" crate.

%files       -n %{name}+tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-stream-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-stream" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-stream-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic" feature of the "%{crate}" crate.

%files       -n %{name}+tonic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic-web-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic-web-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic-web" feature of the "%{crate}" crate.

%files       -n %{name}+tonic-web-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tower-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tower-devel %{_description}

This package contains library source intended for building other packages which
use the "tower" feature of the "%{crate}" crate.

%files       -n %{name}+tower-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tower-http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tower-http-devel %{_description}

This package contains library source intended for building other packages which
use the "tower-http" feature of the "%{crate}" crate.

%files       -n %{name}+tower-http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid" feature of the "%{crate}" crate.

%files       -n %{name}+uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm" feature of the "%{crate}" crate.

%files       -n %{name}+wasm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zerocopy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zerocopy-devel %{_description}

This package contains library source intended for building other packages which
use the "zerocopy" feature of the "%{crate}" crate.

%files       -n %{name}+zerocopy-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
