# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate rmux-pty

Name:           rust-rmux-pty
Version:        0.3.0
Release:        %autorelease
Summary:        PTY allocation, resize, and child-process control for the RMUX terminal multiplexer

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/rmux-pty
Source:         %{crates_source}
# * include license file
# * TODO https://github.com/Helvesec/rmux/pull/XX
Source2:        https://raw.githubusercontent.com/Helvesec/rmux/refs/tags/v%{version}/LICENSE-APACHE
# * include license file
# * TODO https://github.com/Helvesec/rmux/pull/XX
Source3:        https://raw.githubusercontent.com/Helvesec/rmux/refs/tags/v%{version}/LICENSE-MIT
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          rmux-pty-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
PTY allocation, resize, and child-process control for the RMUX terminal
multiplexer.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# copy in license file
cp -p %{SOURCE2} .
cp -p %{SOURCE3} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
