# Generated by go2rpm 1.17.1
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

#%if %{with bootstrap}
#%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
#%endif

# https://github.com/twpayne/chezmoi
%global goipath         github.com/twpayne/chezmoi
Version:                2.64.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Manage your dotfiles across multiple diverse machines, securely.}

%global golicenses      LICENSE
%global godocs          README.md\\\
                        assets/chezmoi.io/snippets/config-format.md\\\
                        assets/chezmoi.io/snippets/common-flags/exclude.md\\\
                        assets/chezmoi.io/snippets/common-flags/format.md\\\
                        assets/chezmoi.io/snippets/common-flags/include.md\\\
                        assets/chezmoi.io/snippets/common-flags/init.md\\\
                        assets/chezmoi.io/snippets/common-flags/nul-path-\\\
                        separator.md assets/chezmoi.io/snippets/common-\\\
                        flags/parent-dirs.md\\\
                        assets/chezmoi.io/snippets/common-flags/path-style.md\\\
                        assets/chezmoi.io/snippets/common-flags/recursive.md\\\
                        assets/chezmoi.io/snippets/common-flags/tree.md

Name:           chezmoi
Release:        %autorelease
Summary:        Manage your dotfiles across multiple diverse machines, securely

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

Patch0:         disable-upgrade.diff

Suggests:       git-core
Suggests:       age
Suggests:       gnupg2
Suggests:       pinentry
Suggests:       gopass
Suggests:       keepassxc
Suggests:       lastpass-cli
Suggests:       pass
Suggests:       rbw
# 1password-command (op) not available
# bitwarden-command (bw) not available
# bitwarden-secrets-command (bws) not available
# dashlane-command (dcli) not available
# doppler-command (doppler) not available
# keeper-command (keeper) not available
# passhole-command (ph) not available
# vault-command (vault) not available


# Why?
BuildRequires:  golang(github.com/blang/semver/v4)
BuildRequires:  golang(github.com/gopasspw/gitconfig)
BuildRequires:  golang(github.com/hashicorp/golang-lru/v2)
BuildRequires:  golang(github.com/caspr-io/yamlpath)
BuildRequires:  golang(github.com/BobuSumisu/aho-corasick)
BuildRequires:  golang(github.com/fatih/semgroup)
BuildRequires:  golang(github.com/rs/zerolog)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(github.com/gitleaks/go-gitdiff/gitdiff)
BuildRequires:  golang(github.com/h2non/filetype)
BuildRequires:  golang(github.com/mholt/archives)


%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1
# disable upgrade
rm  internal/cmd/upgradecmd.go internal/cmd/upgradecmd_test.go internal/cmd/upgradecmd_unix.go internal/cmd/upgradecmd_windows.go

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

#Ref: https://github.com/lihaohong6/COPR/blob/master/chezmoi/chezmoi.spec
# todo other main.XXX variables
# not currently this not work? , so  1) move to %build section 2) use # like golang-github-nvidia-container-toolkit.spec
%if %{without bootstrap}
%build
# To pass the test , set main.version
%define currentgoldflags -X main.version=%{version} ${currentgoldflags}
%gobuild -o %{gobuilddir}/bin/chezmoi %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -Dpm 0644 completions/%{name}-completion.bash %{buildroot}%{bash_completions_dir}/%{name}.bash
install -Dpm 0644 completions/%{name}.fish            -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 completions/%{name}.zsh             %{buildroot}%{zsh_completions_dir}/_%{name}

%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.md
%doc assets/chezmoi.io/snippets/config-format.md
%doc assets/chezmoi.io/snippets/common-flags/exclude.md
%doc assets/chezmoi.io/snippets/common-flags/format.md
%doc assets/chezmoi.io/snippets/common-flags/include.md
%doc assets/chezmoi.io/snippets/common-flags/init.md
%doc assets/chezmoi.io/snippets/common-flags/nul-path-separator.md
%doc assets/chezmoi.io/snippets/common-flags/parent-dirs.md
%doc assets/chezmoi.io/snippets/common-flags/path-style.md
%doc assets/chezmoi.io/snippets/common-flags/recursive.md
%doc assets/chezmoi.io/snippets/common-flags/tree.md
%{_bindir}/chezmoi
%{bash_completions_dir}/%{name}.bash
%{fish_completions_dir}/%{name}.fish
%{zsh_completions_dir}/_%{name}
%endif

%gopkgfiles

%changelog
%autochangelog
