# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate wildcard

Name:           rust-wildcard
Version:        0.3.0
Release:        %autorelease
Summary:        Matching

License:        Apache-2.0
URL:            https://crates.io/crates/wildcard
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop unused, benchmark-only criterion, wildmatch dev-dependency, add feature
#   flag serde_derive for serde
Patch:          wildcard-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Wildcard matching.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/release-notes.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fatal-warnings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fatal-warnings-devel %{_description}

This package contains library source intended for building other packages which
use the "fatal-warnings" feature of the "%{crate}" crate.

%files       -n %{name}+fatal-warnings-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
