[package]
license-files = [
  "LICENSE-APACHE",
  "LICENSE-MIT",
]

[[package.extra-sources]]
number = 2
file = "https://raw.githubusercontent.com/Helvesec/rmux/refs/tags/v%{version}/LICENSE-APACHE"
comments = [
  "include license file",
  "TODO https://github.com/Helvesec/rmux/pull/XX",
]

[[package.extra-sources]]
number = 3
file = "https://raw.githubusercontent.com/Helvesec/rmux/refs/tags/v%{version}/LICENSE-MIT"
comments = [
  "include license file",
  "TODO https://github.com/Helvesec/rmux/pull/XX",
]

[scripts]
prep.post = ["""\
# copy in license file
cp -p %{SOURCE2} .
cp -p %{SOURCE3} ."""]

# use either install.post or add it in `include` section (if exists) of Cargo.toml and 
#install.post = [
#  "cp -p LICENSE-APACHE %{buildroot}%{crate_instdir}/",
#  "cp -p LICENSE-MIT %{buildroot}%{crate_instdir}/",
#]

[tests]
skip = ["request_command_surface_matches_handler_dispatch"]
skip-exact = true
comments = ["skip one test that require files which are not included in published crates"]
