# Generated by rust2rpm 28
%bcond check 1

%global crate boringtun

Name:           rust-boringtun
Version:        0.6.0
Release:        %autorelease
Summary:        Implementation of the WireGuard® protocol designed for portability and speed

License:        BSD-3-Clause
URL:            https://crates.io/crates/boringtun
Source:         %{crates_source}
# * include license file
# * TODO https://github.com/cloudflare/boringtun/pull/XX
Source2:        https://raw.githubusercontent.com/cloudflare/boringtun/refs/tags/%{crate}-%{version}/LICENSE.md

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli

%global _description %{expand:
An implementation of the WireGuard® protocol designed for portability
and speed.}

%description %{_description}

%package     -n libboringtun
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n libboringtun %{_description}

%files       -n libboringtun
%license LICENSE.md
%license LICENSE.dependencies

# a tricky way to append so file with soversion variable to libboringtun
%global soversion 0.6
%{_libdir}/libboringtun.so.%{soversion}

%package     -n libboringtun-devel
Summary:        %{summary}
Requires:       libboringtun%{?_isa} = %{version}-%{release}

%description -n libboringtun-devel %{_description}

%files       -n libboringtun-devel
%{_libdir}/libboringtun.so
%{_includedir}/wireguard_ffi.h

%bcond static 0
%if %{with static}
%package     -n libboringtun-static
Summary:        %{summary}
Requires:       libboringtun-devel%{?_isa} = %{version}-%{release}

%description -n libboringtun-static %{_description}

%files       -n libboringtun-static
%{_libdir}/libboringtun.a
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+device-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+device-devel %{_description}

This package contains library source intended for building other packages which
use the "device" feature of the "%{crate}" crate.

%files       -n %{name}+device-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ffi-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ffi-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "ffi-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+ffi-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jni-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jni-devel %{_description}

This package contains library source intended for building other packages which
use the "jni" feature of the "%{crate}" crate.

%files       -n %{name}+jni-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jni-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jni-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "jni-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+jni-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mock-instant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mock-instant-devel %{_description}

This package contains library source intended for building other packages which
use the "mock-instant" feature of the "%{crate}" crate.

%files       -n %{name}+mock-instant-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mock_instant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mock_instant-devel %{_description}

This package contains library source intended for building other packages which
use the "mock_instant" feature of the "%{crate}" crate.

%files       -n %{name}+mock_instant-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+socket2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+socket2-devel %{_description}

This package contains library source intended for building other packages which
use the "socket2" feature of the "%{crate}" crate.

%files       -n %{name}+socket2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+thiserror-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+thiserror-devel %{_description}

This package contains library source intended for building other packages which
use the "thiserror" feature of the "%{crate}" crate.

%files       -n %{name}+thiserror-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-subscriber-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-subscriber-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing-subscriber" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-subscriber-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
# Adjust dependencies version
tomcli-set Cargo.toml str dependencies.ring.version 0.17
tomcli-set Cargo.toml str dependencies.x25519-dalek.version 2.0.1
tomcli-set Cargo.toml del dev-dependencies.criterion
tomcli-set Cargo.toml str 'target."cfg(unix)".dependencies.nix.version' 0.26
%cargo_prep
# copy in license file
cp -p %{SOURCE2} .
echo 'fn main(){println!("cargo::rustc-link-arg-cdylib=-Wl,-soname,libboringtun.so.%{soversion}");}' > build.rs

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
# install shared library
mkdir -p %{buildroot}/%{_libdir}
cp -pav target/release/libboringtun.so %{buildroot}/%{_libdir}/libboringtun.so.%{soversion}
%if %{with static}
cp -pav target/release/libboringtun.a %{buildroot}/%{_libdir}/libboringtun.a
%endif
mkdir -p %{buildroot}/%{_includedir}
cp -pav src/wireguard_ffi.h %{buildroot}/%{_includedir}/wireguard_ffi.h
ln -s libboringtun.so.%{soversion} %{buildroot}/%{_libdir}/libboringtun.so

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
