# Generated by rust2rpm 27
%bcond check 1

%global crate compiledb

Name:           rust-compiledb
Version:        1.1.0
Release:        %autorelease
Summary:        Clang's Compilation Database generator for make-based build systems

License:        GPL-3.0
URL:            https://crates.io/crates/compiledb
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

Conflicts:      golang-github-fcying-compiledb
Conflicts:      python-compiledb

%global _description %{expand:
Clang's Compilation Database generator for make-based build systems.}

%description %{_description}

# %package     -n %{crate}
# Summary:        %{summary}
# # (MIT OR Apache-2.0) AND Unicode-DFS-2016
# # Apache-2.0 OR BSL-1.0
# # Apache-2.0 OR MIT
# # Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# # GPL-3.0
# # MIT
# # MIT OR Apache-2.0
# # Unlicense OR MIT
# License:        ((MIT OR Apache-2.0) AND Unicode-DFS-2016) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND GPL-3.0 AND MIT AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)
# # LICENSE.dependencies contains a full license breakdown
#
# %description -n %{crate} %{_description}
#
# %files       -n %{crate}

## Use `rust-compiledb` instead of `compiledb` for package name
%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%doc SECURITY.md
%{_bindir}/compiledb

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/SECURITY.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
