# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate v8

# compile and run tests only on supported architectures
%global supported_arches x86_64

Name:           rust-v8
Version:        0.106.0
Release:        %autorelease
Summary:        Rust bindings to V8

License:        MIT
URL:            https://crates.io/crates/v8
Source:         %{crates_source}
Source2:        https://raw.githubusercontent.com/denoland/icu/a22a8f24224ddda8b856437d7e8560de1da3f8e1/common/icudtl.dat
Source3:        https://raw.githubusercontent.com/denoland/icu/a22a8f24224ddda8b856437d7e8560de1da3f8e1/common/icudtb.dat
# Manually created patch for downstream crate metadata changes
# * since we re-package it from crates.io, we won't exclude any files. (and
#   include dot files)
Patch:          v8-fix-metadata.diff
# * for use clang 19 + triple redhat instead of unknown
Patch2:         0001-fix-clang.patch
# * for building from source
Patch3:         0002-set-env-in-build-rs.patch

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  clang >= 19, clang < 20
BuildRequires:  gn
BuildRequires:  ninja-build
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  lld
BuildRequires:  python3-devel

%global _description %{expand:
Rust bindings to V8.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use_custom_libcxx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_custom_libcxx-devel %{_description}

This package contains library source intended for building other packages which
use the "use_custom_libcxx" feature of the "%{crate}" crate.

%files       -n %{name}+use_custom_libcxx-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
mkdir -p third_party/icu/common/
cp -p %{SOURCE2} third_party/icu/common/
cp -p %{SOURCE3} third_party/icu/common/
%py3_shebang_fix .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%ifarch %{supported_arches}
%cargo_build
%endif

%install
%cargo_install

%if %{with check}
%ifarch %{supported_arches}
%check
# * handle_scope_escape_to_nowhere returns different format of error message
%cargo_test -- -- --exact --skip ui
%endif
%endif

%changelog
%autochangelog
