# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate ip_network

Name:           rust-ip_network
Version:        0.4.1
Release:        %autorelease
Summary:        IPv4 and IPv6 network structs

License:        BSD-2-Clause
URL:            https://crates.io/crates/ip_network
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli

%global _description %{expand:
IPv4 and IPv6 network structs.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+diesel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+diesel-devel %{_description}

This package contains library source intended for building other packages which
use the "diesel" feature of the "%{crate}" crate.

%files       -n %{name}+diesel-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+postgres-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+postgres-devel %{_description}

This package contains library source intended for building other packages which
use the "postgres" feature of the "%{crate}" crate.

%files       -n %{name}+postgres-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
# Drop dev-dependencies for benchmark
tomcli-set Cargo.toml del dev-dependencies.criterion
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
