# Generated by rust2rpm 27
%bcond check 1

%global crate erg_compiler

Name:           rust-erg_compiler
Version:        0.6.53
Release:        %autorelease
Summary:        Centimetre: the Erg compiler

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/erg_compiler
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Centimetre: the Erg compiler.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# MIT OR Apache-2.0
License:        MIT OR Apache-2.0
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license lib/LICENCE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/cm

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/lib/LICENCE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+backtrace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+backtrace-devel %{_description}

This package contains library source intended for building other packages which
use the "backtrace" feature of the "%{crate}" crate.

%files       -n %{name}+backtrace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+els-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+els-devel %{_description}

This package contains library source intended for building other packages which
use the "els" feature of the "%{crate}" crate.

%files       -n %{name}+els-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+experimental-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+experimental-devel %{_description}

This package contains library source intended for building other packages which
use the "experimental" feature of the "%{crate}" crate.

%files       -n %{name}+experimental-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-repl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-repl-devel %{_description}

This package contains library source intended for building other packages which
use the "full-repl" feature of the "%{crate}" crate.

%files       -n %{name}+full-repl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gal-devel %{_description}

This package contains library source intended for building other packages which
use the "gal" feature of the "%{crate}" crate.

%files       -n %{name}+gal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+japanese-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+japanese-devel %{_description}

This package contains library source intended for building other packages which
use the "japanese" feature of the "%{crate}" crate.

%files       -n %{name}+japanese-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+large_thread-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+large_thread-devel %{_description}

This package contains library source intended for building other packages which
use the "large_thread" feature of the "%{crate}" crate.

%files       -n %{name}+large_thread-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log-level-error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-level-error-devel %{_description}

This package contains library source intended for building other packages which
use the "log-level-error" feature of the "%{crate}" crate.

%files       -n %{name}+log-level-error-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_std-devel %{_description}

This package contains library source intended for building other packages which
use the "no_std" feature of the "%{crate}" crate.

%files       -n %{name}+no_std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parallel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parallel-devel %{_description}

This package contains library source intended for building other packages which
use the "parallel" feature of the "%{crate}" crate.

%files       -n %{name}+parallel-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pretty-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pretty-devel %{_description}

This package contains library source intended for building other packages which
use the "pretty" feature of the "%{crate}" crate.

%files       -n %{name}+pretty-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+py_compat-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+py_compat-devel %{_description}

This package contains library source intended for building other packages which
use the "py_compat" feature of the "%{crate}" crate.

%files       -n %{name}+py_compat-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pylib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pylib-devel %{_description}

This package contains library source intended for building other packages which
use the "pylib" feature of the "%{crate}" crate.

%files       -n %{name}+pylib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pylib_compiler-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pylib_compiler-devel %{_description}

This package contains library source intended for building other packages which
use the "pylib_compiler" feature of the "%{crate}" crate.

%files       -n %{name}+pylib_compiler-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simplified_chinese-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simplified_chinese-devel %{_description}

This package contains library source intended for building other packages which
use the "simplified_chinese" feature of the "%{crate}" crate.

%files       -n %{name}+simplified_chinese-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+traditional_chinese-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+traditional_chinese-devel %{_description}

This package contains library source intended for building other packages which
use the "traditional_chinese" feature of the "%{crate}" crate.

%files       -n %{name}+traditional_chinese-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicode-devel %{_description}

This package contains library source intended for building other packages which
use the "unicode" feature of the "%{crate}" crate.

%files       -n %{name}+unicode-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
# FIXME: install shared library

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
