# Generated by rust2rpm 27
%bcond check 1

%global crate tree-sitter-md

Name:           rust-tree-sitter-md
Version:        0.3.2
Release:        %autorelease
Summary:        Markdown grammar for tree-sitter

License:        MIT
URL:            https://crates.io/crates/tree-sitter-md
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Markdown grammar for tree-sitter.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/benchmark

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parser-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parser-devel %{_description}

This package contains library source intended for building other packages which
use the "parser" feature of the "%{crate}" crate.

%files       -n %{name}+parser-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tree-sitter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tree-sitter-devel %{_description}

This package contains library source intended for building other packages which
use the "tree-sitter" feature of the "%{crate}" crate.

%files       -n %{name}+tree-sitter-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f parser

%build
%cargo_build -f parser
%{cargo_license_summary -f parser}
%{cargo_license -f parser} > LICENSE.dependencies

%install
%cargo_install -f parser

%if %{with check}
%check
%cargo_test -f parser
%endif

%changelog
%autochangelog
