# Generated by rust2rpm 27
# * construct dependency fast
%bcond check 0

%global crate libsui

Name:           rust-libsui
Version:        0.5.0
Release:        %autorelease
Summary:        Injection tool for executable formats

License:        MIT
URL:            https://crates.io/crates/libsui
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          libsui-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildArch:      x86_64

%global _description %{expand:
A injection tool for executable formats (ELF, PE, Mach-O) that allows
you to embed files into existing binary and extract them at runtime.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/sui

%package        devel
Summary:        %{summary}

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
