# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate libsql-sys

Name:           rust-libsql-sys
Version:        0.9.30
Release:        %autorelease
Summary:        Native bindings to libSQL

License:        MIT
URL:            https://crates.io/crates/libsql-sys
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Native bindings to libSQL.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+api-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+api-devel %{_description}

This package contains library source intended for building other packages which
use the "api" feature of the "%{crate}" crate.

%files       -n %{name}+api-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encryption-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encryption-devel %{_description}

This package contains library source intended for building other packages which
use the "encryption" feature of the "%{crate}" crate.

%files       -n %{name}+encryption-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rusqlite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rusqlite-devel %{_description}

This package contains library source intended for building other packages which
use the "rusqlite" feature of the "%{crate}" crate.

%files       -n %{name}+rusqlite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-crypto-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-crypto-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-crypto" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-crypto-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-fuzzy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-fuzzy-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-fuzzy" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-fuzzy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-math-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-math-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-math" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-math-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-regexp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-regexp-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-regexp" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-regexp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-stats-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-stats-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-stats" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-stats-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-text-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-text-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-text" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-text-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extension-uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extension-uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extension-uuid" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extension-uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlean-extensions-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlean-extensions-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlean-extensions" feature of the "%{crate}" crate.

%files       -n %{name}+sqlean-extensions-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unix-excl-vfs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unix-excl-vfs-devel %{_description}

This package contains library source intended for building other packages which
use the "unix-excl-vfs" feature of the "%{crate}" crate.

%files       -n %{name}+unix-excl-vfs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wal-devel %{_description}

This package contains library source intended for building other packages which
use the "wal" feature of the "%{crate}" crate.

%files       -n %{name}+wal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasmtime-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasmtime-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "wasmtime-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+wasmtime-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
