# Generated by rust2rpm 27
%bcond check 1

%global crate clipboard-sync

Name:           %{crate}
Version:        0.2.0
Release:        %autorelease
Summary:        Synchronizes the clipboard across multiple X11 and wayland instances running on the same machine

License:        MIT OR Apache-2.0
URL:            https://github.com/jackyzy823/clipboard-sync
# use source (cargo package) from current folder
# TODO use original one with patches
Source:         %{crate}-%{version}.crate

## original one
#URL:            https://crates.io/crates/clipboard-sync
#Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
#TODO for x11-clipboard crate
#BuildRequires: libxcb-devel
BuildRequires: systemd-rpm-macros

%global _description %{expand:
Synchronizes the clipboard across multiple X11 and wayland instances
running on the same machine.}

%description %{_description}

%files
%license LICENSE.dependencies
%doc README.md
%{_bindir}/clipboard-sync
%{_userunitdir}/clipboard-sync.service

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dpm0644 clipboard-sync.service -t %{buildroot}%{_userunitdir}

%post
%systemd_user_post clipboard-sync.service

%preun
%systemd_user_preun clipboard-sync.service

%postun
%systemd_user_postun_with_restart clipboard-sync.service

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
