# Generated by go2rpm 1.17.1
%bcond check 1

# https://github.com/twpayne/chezmoi
%global goipath         github.com/twpayne/chezmoi
%global release_commit	9b1def1eff7c581272ffeb7f707e7af80ec434b1
Version:                2.64.0

%gometa -L -f


Name:           chezmoi
Release:        %autorelease
Summary:        Manage your dotfiles across multiple diverse machines, securely

# Generated by go-vendor-tools
License:        0BSD AND Apache-2.0 AND BSD-2-Clause AND BSD-2-Clause-Views AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

Suggests:       git-core
Suggests:       age
Suggests:       gnupg2
Suggests:       pinentry
Suggests:       gopass
Suggests:       keepassxc
Suggests:       lastpass-cli
Suggests:       pass
Suggests:       rbw
# 1password-command (op) not available
# bitwarden-command (bw) not available
# bitwarden-secrets-command (bws) not available
# dashlane-command (dcli) not available
# doppler-command (doppler) not available
# keeper-command (keeper) not available
# passhole-command (ph) not available
# vault-command (vault) not available

%description
Manage your dotfiles across multiple diverse machines, securely.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
export GO_LDFLAGS="-X main.version=%{version} \
			-X main.builtBy=Copr  \
			-X main.commit=%{release_commit} \
			-X main.date=$(date -d "@${SOURCE_DATE_EPOCH}" +%Y-%m-%dT%H:%M:%SZ)"
export GO_BUILDTAGS="noupgrade"
%gobuild -o %{gobuilddir}/bin/chezmoi %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -Dpm 0644 completions/%{name}-completion.bash %{buildroot}%{bash_completions_dir}/%{name}.bash
install -Dpm 0644 completions/%{name}.fish            -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 completions/%{name}.zsh             %{buildroot}%{zsh_completions_dir}/_%{name}

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%doc assets/chezmoi.io/snippets/config-format.md
%doc assets/chezmoi.io/snippets/common-flags/exclude.md
%doc assets/chezmoi.io/snippets/common-flags/format.md
%doc assets/chezmoi.io/snippets/common-flags/include.md
%doc assets/chezmoi.io/snippets/common-flags/init.md
%doc assets/chezmoi.io/snippets/common-flags/nul-path-separator.md
%doc assets/chezmoi.io/snippets/common-flags/parent-dirs.md
%doc assets/chezmoi.io/snippets/common-flags/path-style.md
%doc assets/chezmoi.io/snippets/common-flags/recursive.md
%doc assets/chezmoi.io/snippets/common-flags/tree.md
%{_bindir}/chezmoi
%{bash_completions_dir}/%{name}.bash
%{fish_completions_dir}/%{name}.fish
%{zsh_completions_dir}/_%{name}


%changelog
%autochangelog
