# Generated by go2rpm 1.17.1
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/sorairolake/lzip-go
%global goipath         github.com/sorairolake/lzip-go
Version:                0.3.7

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Pure Go implementation for reading and writing lzip format compressed files.}

%global golicenses      LICENSE-APACHE LICENSE-MIT LICENSES/BSD-2-Clause.txt\\\
                        LICENSES/CC-BY-4.0.txt
%global godocs          docs AUTHORS.adoc CHANGELOG.adoc CODE_OF_CONDUCT.md\\\
                        README.md LICENSES/Apache-2.0.txt LICENSES/MIT.txt

Name:           golang-github-sorairolake-lzip
Release:        %autorelease
Summary:        Pure Go implementation for reading and writing lzip format compressed files

License:        Apache-2.0 AND BSD-2-Clause AND CC-BY-4.0 AND MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE-APACHE LICENSE-MIT LICENSES/BSD-2-Clause.txt
%license LICENSES/CC-BY-4.0.txt
%doc docs AUTHORS.adoc CHANGELOG.adoc CODE_OF_CONDUCT.md README.md
%doc LICENSES/Apache-2.0.txt LICENSES/MIT.txt
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should not use globs to avoid installing conflicting
# binaries.
# Write a _bindir line per each of the binaries the package will install.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
