# Generated by rust2rpm 27
# * construct dependency fast
%bcond check 0
%global debug_package %{nil}

%global crate deno_core

Name:           rust-deno_core
Version:        0.318.0
Release:        %autorelease
Summary:        Modern JavaScript/TypeScript runtime built with V8, Rust, and Tokio

License:        MIT
URL:            https://crates.io/crates/deno_core
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A modern JavaScript/TypeScript runtime built with V8, Rust, and Tokio.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deno_core_icudata-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deno_core_icudata-devel %{_description}

This package contains library source intended for building other packages which
use the "deno_core_icudata" feature of the "%{crate}" crate.

%files       -n %{name}+deno_core_icudata-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+include_icu_data-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+include_icu_data-devel %{_description}

This package contains library source intended for building other packages which
use the "include_icu_data" feature of the "%{crate}" crate.

%files       -n %{name}+include_icu_data-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+include_js_files_for_snapshotting-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+include_js_files_for_snapshotting-devel %{_description}

This package contains library source intended for building other packages which
use the "include_js_files_for_snapshotting" feature of the "%{crate}" crate.

%files       -n %{name}+include_js_files_for_snapshotting-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+snapshot_flags_eager_parse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+snapshot_flags_eager_parse-devel %{_description}

This package contains library source intended for building other packages which
use the "snapshot_flags_eager_parse" feature of the "%{crate}" crate.

%files       -n %{name}+snapshot_flags_eager_parse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unsafe_runtime_options-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unsafe_runtime_options-devel %{_description}

This package contains library source intended for building other packages which
use the "unsafe_runtime_options" feature of the "%{crate}" crate.

%files       -n %{name}+unsafe_runtime_options-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unsafe_use_unprotected_platform-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unsafe_use_unprotected_platform-devel %{_description}

This package contains library source intended for building other packages which
use the "unsafe_use_unprotected_platform" feature of the "%{crate}" crate.

%files       -n %{name}+unsafe_use_unprotected_platform-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v8_use_custom_libcxx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v8_use_custom_libcxx-devel %{_description}

This package contains library source intended for building other packages which
use the "v8_use_custom_libcxx" feature of the "%{crate}" crate.

%files       -n %{name}+v8_use_custom_libcxx-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
chmod -x rebuild_async_stubs.js
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
