# Generated by rust2rpm 27
# * Disable tests because of missing test data (excluded in Cargo.toml by
#   upstream)
%bcond check 0
%global debug_package %{nil}

%global crate fuser

Name:           rust-fuser
Version:        0.13.0
Release:        %autorelease
Summary:        Filesystem in Userspace (FUSE) for Rust

License:        MIT
URL:            https://crates.io/crates/fuser
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          fuser-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(fuse3)

%global _description %{expand:
Filesystem in Userspace (FUSE) for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-10-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-10" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-10-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-11-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-11-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-11" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-11-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-12-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-12" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-13-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-13-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-13" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-13-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-14-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-14" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-14-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-15-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-15-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-15" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-15-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-16-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-16-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-16" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-16-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-17-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-17-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-17" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-17-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-18-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-18-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-18" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-18-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-19-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-19-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-19" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-19-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-20-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-20-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-20" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-20-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-21-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-21-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-21" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-21-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-22-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-22-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-22" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-22-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-23-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-23-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-23" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-23-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-24-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-24-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-24" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-24-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-25-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-25-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-25" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-25-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-26-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-26-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-26" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-26-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-27-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-27-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-27" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-27-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-28-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-28-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-28" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-28-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-29-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-29-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-29" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-29-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-30-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-30-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-30" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-30-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-31-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-31-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-31" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-31-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+abi-7-9-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+abi-7-9-devel %{_description}

This package contains library source intended for building other packages which
use the "abi-7-9" feature of the "%{crate}" crate.

%files       -n %{name}+abi-7-9-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libfuse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libfuse-devel %{_description}

This package contains library source intended for building other packages which
use the "libfuse" feature of the "%{crate}" crate.

%files       -n %{name}+libfuse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pkg-config-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pkg-config-devel %{_description}

This package contains library source intended for building other packages which
use the "pkg-config" feature of the "%{crate}" crate.

%files       -n %{name}+pkg-config-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serializable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serializable-devel %{_description}

This package contains library source intended for building other packages which
use the "serializable" feature of the "%{crate}" crate.

%files       -n %{name}+serializable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
