# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate ratatui-rmux

Name:           rust-ratatui-rmux
Version:        0.3.1
Release:        %autorelease
Summary:        Ratatui integration crate for the RMUX terminal multiplexer that paints daemon-backed pane state into a ratatui Buffer

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/ratatui-rmux
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Ratatui integration crate for the RMUX terminal multiplexer that paints
daemon-backed pane state into a ratatui Buffer.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip one test that require files which are not included in published crates
# * skip one test that requires original Cargo.toml
# * skip one test that requires CARGO_BIN_EXE_rmux env set to the built `rmux`
#   binary path
%{cargo_test -- -- --exact %{shrink:
    --skip enforcement_script_exists
    --skip manifest_direct_dependencies_within_budget
    --skip ratatui_real_daemon_render_smoke
}}
%endif

%changelog
%autochangelog
