# Generated by rust2rpm 28
%bcond check 0

%global crate minidump-stackwalk

Name:           rust-minidump-stackwalk
Version:        0.26.1
Release:        %autorelease
Summary:        Analyzes minidumps and produces a report (either human-readable or JSON)

License:        MIT
URL:            https://crates.io/crates/minidump-stackwalk
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          minidump-stackwalk-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Analyzes minidumps and produces a report (either human-readable or
JSON).}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/minidump-stackwalk

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
