# Generated by rust2rpm 27
%bcond check 1

%global crate mergiraf

Name:           %{crate}
Version:        0.15.0
Release:        %autorelease
Summary:        Syntax-aware merge driver for Git

License:        GPL-3.0-only
URL:            https://crates.io/crates/mergiraf
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          mergiraf-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A syntax-aware merge driver for Git.}

%description %{_description}

%files
%license LICENSE.txt
%license LICENSE.dependencies
%doc CONTRIBUTING.md
%doc GOVERNANCE.md
%doc README.md
%{_bindir}/mergiraf

%package        -n rust-%{name}-devel
Summary:        %{summary}
BuildArch:      noarch

%description    -n rust-%{name}-devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          -n rust-%{name}-devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/GOVERNANCE.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n rust-%{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n rust-%{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+cc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+cc-devel %{_description}

This package contains library source intended for building other packages which
use the "cc" feature of the "%{crate}" crate.

%files       -n rust-%{name}+cc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+dev-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+dev-devel %{_description}

This package contains library source intended for building other packages which
use the "dev" feature of the "%{crate}" crate.

%files       -n rust-%{name}+dev-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
