# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate wezterm-blob-leases

Name:           rust-wezterm-blob-leases
Version:        0.1.1
Release:        %autorelease
Summary:        Manage image blob caching/leasing for wezterm

License:        MIT
URL:            https://crates.io/crates/wezterm-blob-leases
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Manage image blob caching/leasing for wezterm.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simple_tempdir-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simple_tempdir-devel %{_description}

This package contains library source intended for building other packages which
use the "simple_tempdir" feature of the "%{crate}" crate.

%files       -n %{name}+simple_tempdir-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
