# Generated by go2rpm 1.18.0
%bcond check 1

# go2rpm -L -p vendor  --download --name kapp carvel.dev/kapp --forge https://github.com/carvel-dev/kapp

# https://github.com/carvel-dev/kapp
%global goipath         carvel.dev/kapp
%global forgeurl        https://github.com/carvel-dev/kapp
Version:                0.64.2

%gometa -L -f


Name:           kapp
Release:        %autorelease
Summary:        Kapp is a simple deployment tool focused on the concept of "Kubernetes application" — a set of resources with the same label

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Kapp is a simple deployment tool focused on the concept of "Kubernetes
application" — a set of resources with the same label.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
export GO_LDFLAGS="-X carvel.dev/kapp/pkg/kapp/version.Version=%{version} -buildid="
%global gomodulesmode GO111MODULE=on
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
## not possible to do e2e tests
rm -rf test/e2e
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs examples CODE_OF_CONDUCT.md CONTRIBUTING.md GOVERNANCE.md
%doc MAINTAINERS.md README.md ROADMAP.md SECURITY.md code-header-template.txt
%{_bindir}/kapp


%changelog
%autochangelog
