# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate aya

Name:           rust-aya
Version:        0.13.1
Release:        %autorelease
Summary:        EBPF library with a focus on developer experience and operability

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/aya
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An eBPF library with a focus on developer experience and operability.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/BREAKING-CHANGES.md
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async_std-devel %{_description}

This package contains library source intended for building other packages which
use the "async_std" feature of the "%{crate}" crate.

%files       -n %{name}+async_std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async_tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async_tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "async_tokio" feature of the "%{crate}" crate.

%files       -n %{name}+async_tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
