# Generated by go2rpm 1.18.0
%bcond check 1
# go2rpm cmd
# go2rpm -L -p vendor github.com/urnetwork/proxy  --download  -v 2025.12.21~815380930 -c fba5067dcee4480365fc12715228a1366f73fa5a

# https://gitlab.com/fedora/sigs/go/go-vendor-tools/-/issues/92
# currently, license check will failed due to no LICENSE under root folder.
%global go_vendor_license_check_disable 1
# however go2rpm has no option to pass --no-check to go_vendor_license,
# so it will always fail when creating spec and generating vendor archive.

# https://github.com/urnetwork/proxy
%global goipath         github.com/urnetwork/proxy
Version:                2025.12.21~815380930
%global commit          fba5067dcee4480365fc12715228a1366f73fa5a

%gometa -L -f


Name:           golang-github-urnetwork-proxy
Release:        %autorelease
Summary:        None

# Generated by go-vendor-tools
License:        TODO: %{warn:Please fill in the License tag!}
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
# FIXME

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
# Modification: set to off
%global gomodulesmode GO111MODULE=off
# Modification: add package prefix to binary file name
for cmd in v2025/http v2025/socks v2025/wg; do
  %gobuild -o %{gobuilddir}/bin/urnetwork-proxy-$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%global gomodulesmode GO111MODULE=on
# Modification: go to subfolder
cd v2025
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license v2025/vendor/modules.txt
%doc v2025/README.md v2025/http/README.md v2025/socks/README.md
%doc v2025/wg/EXAMPLE_SETUP.md
%{_bindir}/urnetwork-proxy-http
%{_bindir}/urnetwork-proxy-socks
%{_bindir}/urnetwork-proxy-wg


%changelog
%autochangelog
