# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate tree-sitter-scala

Name:           rust-tree-sitter-scala
Version:        0.24.0
Release:        %autorelease
Summary:        Scala grammar for tree-sitter

License:        MIT
URL:            https://crates.io/crates/tree-sitter-scala
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Scala grammar for tree-sitter.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/node_modules/base64-js/LICENSE
%license %{crate_instdir}/node_modules/buffer/LICENSE
%license %{crate_instdir}/node_modules/chownr/LICENSE
%license %{crate_instdir}/node_modules/end-of-stream/LICENSE
%license %{crate_instdir}/node_modules/fs-constants/LICENSE
%license %{crate_instdir}/node_modules/ieee754/LICENSE
%license %{crate_instdir}/node_modules/inherits/LICENSE
%license %{crate_instdir}/node_modules/minimist/LICENSE
%license %{crate_instdir}/node_modules/mkdirp-classic/LICENSE
%license %{crate_instdir}/node_modules/node-abi/LICENSE
%license %{crate_instdir}/node_modules/node-gyp-build/LICENSE
%license %{crate_instdir}/node_modules/once/LICENSE
%license %{crate_instdir}/node_modules/prebuildify/LICENSE
%license %{crate_instdir}/node_modules/prettier/LICENSE
%license %{crate_instdir}/node_modules/pump/LICENSE
%license %{crate_instdir}/node_modules/readable-stream/LICENSE
%license %{crate_instdir}/node_modules/safe-buffer/LICENSE
%license %{crate_instdir}/node_modules/semver/LICENSE
%license %{crate_instdir}/node_modules/string_decoder/LICENSE
%license %{crate_instdir}/node_modules/tar-fs/LICENSE
%license %{crate_instdir}/node_modules/tar-stream/LICENSE
%license %{crate_instdir}/node_modules/tree-sitter-cli/LICENSE
%license %{crate_instdir}/node_modules/tree-sitter/LICENSE
%license %{crate_instdir}/node_modules/util-deprecate/LICENSE
%license %{crate_instdir}/node_modules/wrappy/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
