# Generated by go2rpm 1.17.1
%bcond check 1

# https://github.com/control-theory/gonzo
%global goipath         github.com/control-theory/gonzo
Version:                0.2.1

%gometa -L -f


Name:           golang-github-control-theory-gonzo
Release:        %autorelease
Summary:        Gonzo! The Go based TUI log analysis tool

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Gonzo! The Go based TUI log analysis tool.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs examples CHANGELOG.md CONTRIBUTING.md README.md USAGE_GUIDE.md
%doc guides/CLOUDWATCH_USAGE_GUIDE.md guides/CUSTOM_FORMATS.md
%doc guides/FORMAT_QUICK_REFERENCE.md guides/SKINS.md
%doc guides/STERN_USAGE_GUIDE.md guides/VICTORIA_LOGS_USAGE.md
%{_bindir}/gonzo


%changelog
%autochangelog
