# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate deltae

Name:           rust-deltae
Version:        0.3.2
Release:        %autorelease
Summary:        Calculate Delta E between two colors in CIE Lab space

License:        MIT
URL:            https://crates.io/crates/deltae
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Calculate Delta E between two colors in CIE Lab space.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/docs/doc/COPYRIGHT.txt
%license %{crate_instdir}/docs/doc/FiraSans-LICENSE.txt
%license %{crate_instdir}/docs/doc/LICENSE-APACHE.txt
%license %{crate_instdir}/docs/doc/LICENSE-MIT.txt
%license %{crate_instdir}/docs/doc/SourceCodePro-LICENSE.txt
%license %{crate_instdir}/docs/doc/SourceSerif4-LICENSE.md
%license %{crate_instdir}/docs/doc/noto-sans-kr-v13-korean-regular-LICENSE.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
