# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate boringtun

Name:           rust-boringtun
Version:        0.6.0
Release:        %autorelease
Summary:        Implementation of the WireGuard® protocol designed for portability and speed

License:        BSD-3-Clause
URL:            https://crates.io/crates/boringtun
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          boringtun-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An implementation of the WireGuard® protocol designed for portability
and speed.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+device-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+device-devel %{_description}

This package contains library source intended for building other packages which
use the "device" feature of the "%{crate}" crate.

%files       -n %{name}+device-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ffi-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ffi-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "ffi-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+ffi-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jni-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jni-devel %{_description}

This package contains library source intended for building other packages which
use the "jni" feature of the "%{crate}" crate.

%files       -n %{name}+jni-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jni-bindings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jni-bindings-devel %{_description}

This package contains library source intended for building other packages which
use the "jni-bindings" feature of the "%{crate}" crate.

%files       -n %{name}+jni-bindings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mock-instant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mock-instant-devel %{_description}

This package contains library source intended for building other packages which
use the "mock-instant" feature of the "%{crate}" crate.

%files       -n %{name}+mock-instant-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mock_instant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mock_instant-devel %{_description}

This package contains library source intended for building other packages which
use the "mock_instant" feature of the "%{crate}" crate.

%files       -n %{name}+mock_instant-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+socket2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+socket2-devel %{_description}

This package contains library source intended for building other packages which
use the "socket2" feature of the "%{crate}" crate.

%files       -n %{name}+socket2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+thiserror-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+thiserror-devel %{_description}

This package contains library source intended for building other packages which
use the "thiserror" feature of the "%{crate}" crate.

%files       -n %{name}+thiserror-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-subscriber-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-subscriber-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing-subscriber" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-subscriber-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
# FIXME: install shared library

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
