# Generated by go2rpm 1.19.0
%bcond check 1

# https://github.com/zmap/zgrab2
%global goipath         github.com/zmap/zgrab2
Version:                1.0.0

%gometa -L -f


Name:           zgrab2
Release:        %autorelease
Summary:        Fast Application Layer Scanner

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

Patch0: 0001-fix-tests-pass-TestNewPublicKey.patch
Patch1: 0002-fix-tests-pass-TestValidateCert.patch
Patch2: 0003-fix-tests-pass-TestClientAuthPublicKey.patch
Patch3: 0004-fix-tests-fix-http-redirect-related-tests.patch
Patch4: 0005-fix-tests-fix-address-already-in-use-issue.patch
Patch5: 0006-fix-tests-pass-TestKeyExchange.patch
Patch6: 0007-fix-tests-enable-all-tests-in-Makefile.patch

BuildRequires:  go-vendor-tools

%description
Fast Application Layer Scanner.

%prep
%goprep -p1
tar -xf %{S:1}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
# for cmd in integration_tests/http/http_version_tests/h2c lib/http lib/http2/h2i lib/http2/hpack; do
#   %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
# done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
# %gotest ./...
%gotest -v -failfast .

make test
%endif

%files -f %{go_vendor_license_filelist}
%doc README.md
# %doc README.md requirements.txt integration_tests/.template/README.md
# %doc integration_tests/http/http_version_tests/README.md
# %doc integration_tests/postgres/container/README.md lib/http2/h2i/README.md
# %doc lib/smb/README.md lib/smb/about.txt zgrab2_schemas/README.md
# %{_bindir}/h2c
# %{_bindir}/h2i
# %{_bindir}/hpack
# %{_bindir}/http
%{_bindir}/zgrab2


%changelog
%autochangelog
