# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate grammers-crypto

Name:           rust-grammers-crypto
Version:        0.9.0
Release:        %autorelease
Summary:        Several cryptographic utilities to work with Telegram's data

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/grammers-crypto
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          grammers-crypto-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Several cryptographic utilities to work with Telegram's data.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/DEPS.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
