# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate mitmproxy-highlight

Name:           rust-mitmproxy-highlight
Version:        0.12.6
Release:        %autorelease
Summary:        This crate contains the syntax highlighting backend for mitmproxy and mitmdump, utilizing tree-sitter.

License:        MIT
URL:            https://github.com/mitmproxy/mitmproxy-rs
Source:         https://files.pythonhosted.org/packages/source/m/mitmproxy_rs/mitmproxy_rs-%{version}.tar.gz

# use tomcli instead patch
# Patch0:         metadata.diff
BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli

%global _description %{expand:
%summary}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n mitmproxy_rs-%{version} -p1
## edit target Cargo.toml
## common del
tomcli-set %{crate}/Cargo.toml del package.authors.workspace
tomcli-set %{crate}/Cargo.toml del package.version.workspace
tomcli-set %{crate}/Cargo.toml del package.repository.workspace
tomcli-set %{crate}/Cargo.toml del package.edition.workspace
tomcli-set %{crate}/Cargo.toml del package.rust-version.workspace
tomcli-set %{crate}/Cargo.toml del package.publish.workspace

tomcli-set %{crate}/Cargo.toml del lints

tomcli-set %{crate}/Cargo.toml str package.version `tomcli-get Cargo.toml workspace.package.version`
# False to lowercase with -F json
tomcli-set %{crate}/Cargo.toml `tomcli-get -F json Cargo.toml workspace.package.publish` package.publish
tomcli-set %{crate}/Cargo.toml str package.repository `tomcli-get Cargo.toml workspace.package.repository`
tomcli-set %{crate}/Cargo.toml str package.edition `tomcli-get Cargo.toml workspace.package.edition`
tomcli-set %{crate}/Cargo.toml str package.rust-version `tomcli-get Cargo.toml workspace.package.rust-version`

# TODO add description in Cargo.toml

# add license
cp LICENSE %{crate}
tomcli-set %{crate}/Cargo.toml str package.license-file LICENSE
# create list
tomcli-set %{crate}/Cargo.toml list package.authors
OLD_IFS="$IFS"
IFS=$'\n'
for i in `tomcli-get -F newline-list Cargo.toml workspace.package.authors`
do
tomcli-set %{crate}/Cargo.toml append package.authors "$i"
done
IFS="$OLD_IFS"
# edit dep
tomcli-set %{crate}/Cargo.toml del dev-dependencies.criterion

##
rm Cargo.toml
%cargo_prep

%generate_buildrequires
cd %{crate}
%cargo_generate_buildrequires

%build
cd %{crate}
%cargo_build

%install
cd %{crate}
%cargo_install

%if %{with check}
%check
cd %{crate}
%cargo_test
%endif

%changelog
%autochangelog
