# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate grammers-tl-types

Name:           rust-grammers-tl-types
Version:        0.9.0
Release:        %autorelease
Summary:        Rust definitions for Telegram's API types and functions

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/grammers-tl-types
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          grammers-tl-types-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust definitions for Telegram's API types and functions.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deserializable-functions-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deserializable-functions-devel %{_description}

This package contains library source intended for building other packages which
use the "deserializable-functions" feature of the "%{crate}" crate.

%files       -n %{name}+deserializable-functions-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+impl-debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+impl-debug-devel %{_description}

This package contains library source intended for building other packages which
use the "impl-debug" feature of the "%{crate}" crate.

%files       -n %{name}+impl-debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+impl-from-enum-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+impl-from-enum-devel %{_description}

This package contains library source intended for building other packages which
use the "impl-from-enum" feature of the "%{crate}" crate.

%files       -n %{name}+impl-from-enum-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+impl-from-type-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+impl-from-type-devel %{_description}

This package contains library source intended for building other packages which
use the "impl-from-type" feature of the "%{crate}" crate.

%files       -n %{name}+impl-from-type-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+impl-serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+impl-serde-devel %{_description}

This package contains library source intended for building other packages which
use the "impl-serde" feature of the "%{crate}" crate.

%files       -n %{name}+impl-serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tl-api-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tl-api-devel %{_description}

This package contains library source intended for building other packages which
use the "tl-api" feature of the "%{crate}" crate.

%files       -n %{name}+tl-api-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tl-mtproto-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tl-mtproto-devel %{_description}

This package contains library source intended for building other packages which
use the "tl-mtproto" feature of the "%{crate}" crate.

%files       -n %{name}+tl-mtproto-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
