# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/wagoodman/dive
%global goipath         github.com/wagoodman/dive
Version:                0.13.1

%gometa -L -f


Name:           dive
Release:        %autorelease
Summary:        A tool for exploring each layer in a docker image

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT AND Unlicense
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
A tool for exploring each layer in a docker image.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
# These cmds are not standalone
#for cmd in cmd/* ; do
#  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
#done
%gobuild -o %{gobuilddir}/bin/dive %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md RELEASE.md
%{_bindir}/dive


%changelog
%autochangelog
