# Generated by rust2rpm 27
# * skip criterion
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

Name:           edit
Version:        1.2.0
Release:        %autorelease
Summary:        A simple editor for simple needs (Microsoft Edit).

SourceLicense:  MIT
License:        MIT OR Apache-2.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/microsoft/edit
Source:         https://github.com/microsoft/edit/archive/v%{version}/edit-v%{version}.tar.gz
# Automatically generated patch to strip dependencies and normalize metadata
Patch0:          edit-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n edit-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%doc SECURITY.md
%{_bindir}/edit
# TODO desktop files and icons
# Guildeline https://docs.fedoraproject.org/en-US/packaging-guidelines/#_desktop_files
# see https://packages.aosc.io/files/amd64/stable/edit/1.0.0-1 and https://github.com/AOSC-Dev/aosc-os-abbs/blob/stable/app-editors/edit/autobuild/patches/0004-feat-assets-add-a-.desktop-entry.patch

%changelog
%autochangelog
