# Generated by rust2rpm 27
# * Disable tests because of missing test data (excluded in Cargo.toml by
#   upstream)
%bcond check 0
%global debug_package %{nil}

%global crate age

Name:           rust-age
Version:        0.11.1
Release:        %autorelease
Summary:        [BETA] A simple, secure, and modern encryption library

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/age
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          age-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
[BETA] A simple, secure, and modern encryption library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aes-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes-devel %{_description}

This package contains library source intended for building other packages which
use the "aes" feature of the "%{crate}" crate.

%files       -n %{name}+aes-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aes-gcm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aes-gcm-devel %{_description}

This package contains library source intended for building other packages which
use the "aes-gcm" feature of the "%{crate}" crate.

%files       -n %{name}+aes-gcm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+armor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+armor-devel %{_description}

This package contains library source intended for building other packages which
use the "armor" feature of the "%{crate}" crate.

%files       -n %{name}+armor-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-devel %{_description}

This package contains library source intended for building other packages which
use the "async" feature of the "%{crate}" crate.

%files       -n %{name}+async-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bcrypt-pbkdf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bcrypt-pbkdf-devel %{_description}

This package contains library source intended for building other packages which
use the "bcrypt-pbkdf" feature of the "%{crate}" crate.

%files       -n %{name}+bcrypt-pbkdf-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cbc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cbc-devel %{_description}

This package contains library source intended for building other packages which
use the "cbc" feature of the "%{crate}" crate.

%files       -n %{name}+cbc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cipher-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cipher-devel %{_description}

This package contains library source intended for building other packages which
use the "cipher" feature of the "%{crate}" crate.

%files       -n %{name}+cipher-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cli-common-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cli-common-devel %{_description}

This package contains library source intended for building other packages which
use the "cli-common" feature of the "%{crate}" crate.

%files       -n %{name}+cli-common-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+console-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+console-devel %{_description}

This package contains library source intended for building other packages which
use the "console" feature of the "%{crate}" crate.

%files       -n %{name}+console-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ctr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ctr-devel %{_description}

This package contains library source intended for building other packages which
use the "ctr" feature of the "%{crate}" crate.

%files       -n %{name}+ctr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+curve25519-dalek-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+curve25519-dalek-devel %{_description}

This package contains library source intended for building other packages which
use the "curve25519-dalek" feature of the "%{crate}" crate.

%files       -n %{name}+curve25519-dalek-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-devel %{_description}

This package contains library source intended for building other packages which
use the "futures" feature of the "%{crate}" crate.

%files       -n %{name}+futures-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+is-terminal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+is-terminal-devel %{_description}

This package contains library source intended for building other packages which
use the "is-terminal" feature of the "%{crate}" crate.

%files       -n %{name}+is-terminal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+memchr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+memchr-devel %{_description}

This package contains library source intended for building other packages which
use the "memchr" feature of the "%{crate}" crate.

%files       -n %{name}+memchr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+num-traits-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num-traits-devel %{_description}

This package contains library source intended for building other packages which
use the "num-traits" feature of the "%{crate}" crate.

%files       -n %{name}+num-traits-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pinentry-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pinentry-devel %{_description}

This package contains library source intended for building other packages which
use the "pinentry" feature of the "%{crate}" crate.

%files       -n %{name}+pinentry-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+plugin-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+plugin-devel %{_description}

This package contains library source intended for building other packages which
use the "plugin" feature of the "%{crate}" crate.

%files       -n %{name}+plugin-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rpassword-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rpassword-devel %{_description}

This package contains library source intended for building other packages which
use the "rpassword" feature of the "%{crate}" crate.

%files       -n %{name}+rpassword-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rsa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rsa-devel %{_description}

This package contains library source intended for building other packages which
use the "rsa" feature of the "%{crate}" crate.

%files       -n %{name}+rsa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ssh-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ssh-devel %{_description}

This package contains library source intended for building other packages which
use the "ssh" feature of the "%{crate}" crate.

%files       -n %{name}+ssh-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+web-sys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+web-sys-devel %{_description}

This package contains library source intended for building other packages which
use the "web-sys" feature of the "%{crate}" crate.

%files       -n %{name}+web-sys-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+which-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+which-devel %{_description}

This package contains library source intended for building other packages which
use the "which" feature of the "%{crate}" crate.

%files       -n %{name}+which-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wsl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wsl-devel %{_description}

This package contains library source intended for building other packages which
use the "wsl" feature of the "%{crate}" crate.

%files       -n %{name}+wsl-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
