# Generated by rust2rpm 27
%bcond check 1

%global crate ratatui-image

Name:           rust-ratatui-image
Version:        1.0.5
Release:        %autorelease
Summary:        Image widget for ratatui, supporting sixels and unicode-halfblocks

License:        MIT
URL:            https://crates.io/crates/ratatui-image
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          ratatui-image-fix-metadata.diff
Patch1:		ignore-doctest.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An image widget for ratatui, supporting sixels and unicode-halfblocks.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
# 0BSD OR MIT OR Apache-2.0
# Apache-2.0
# Apache-2.0 OR BSL-1.0
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause
# BSD-2-Clause AND ISC
# BSD-2-Clause OR Apache-2.0 OR MIT
# BSD-3-Clause
# MIT
# MIT OR Apache-2.0
# MIT OR Apache-2.0 OR Zlib
# MIT OR Zlib OR Apache-2.0
# Unlicense OR MIT
# Zlib
# Zlib OR Apache-2.0 OR MIT
License:        Zlib AND Apache-2.0 AND BSD-2-Clause AND ISC AND BSD-3-Clause AND MIT AND (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND (MIT OR Apache-2.0) AND (MIT OR Apache-2.0 OR Zlib) AND (MIT OR Zlib OR Apache-2.0) AND (Unlicense OR MIT) AND (Zlib OR Apache-2.0 OR MIT)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/ratatui-image

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+crossterm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crossterm-devel %{_description}

This package contains library source intended for building other packages which
use the "crossterm" feature of the "%{crate}" crate.

%files       -n %{name}+crossterm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-defaults-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-defaults-devel %{_description}

This package contains library source intended for building other packages which
use the "image-defaults" feature of the "%{crate}" crate.

%files       -n %{name}+image-defaults-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustix-devel %{_description}

This package contains library source intended for building other packages which
use the "rustix" feature of the "%{crate}" crate.

%files       -n %{name}+rustix-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+termion-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+termion-devel %{_description}

This package contains library source intended for building other packages which
use the "termion" feature of the "%{crate}" crate.

%files       -n %{name}+termion-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+termwiz-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+termwiz-devel %{_description}

This package contains library source intended for building other packages which
use the "termwiz" feature of the "%{crate}" crate.

%files       -n %{name}+termwiz-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f crossterm

%build
%cargo_build -f crossterm
%{cargo_license_summary -f crossterm}
%{cargo_license -f crossterm} > LICENSE.dependencies

%install
%cargo_install -f crossterm

%if %{with check}
%check
%cargo_test -f crossterm
%endif

%changelog
%autochangelog
