# Generated by rust2rpm 27
%bcond check 1

%global crate els

Name:           %{crate}
Version:        0.1.65
Release:        %autorelease
Summary:        Erg compiler frontend for IDEs, implements LSP

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/els
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          els-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An Erg compiler frontend for IDEs, implements LSP.}

%description %{_description}

%files
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/els

%package        -n rust-%{name}-devel
Summary:        %{summary}
BuildArch:      noarch

%description    -n rust-%{name}-devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          -n rust-%{name}-devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n rust-%{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n rust-%{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+backtrace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+backtrace-devel %{_description}

This package contains library source intended for building other packages which
use the "backtrace" feature of the "%{crate}" crate.

%files       -n rust-%{name}+backtrace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n rust-%{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+experimental-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+experimental-devel %{_description}

This package contains library source intended for building other packages which
use the "experimental" feature of the "%{crate}" crate.

%files       -n rust-%{name}+experimental-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+japanese-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+japanese-devel %{_description}

This package contains library source intended for building other packages which
use the "japanese" feature of the "%{crate}" crate.

%files       -n rust-%{name}+japanese-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+large_thread-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+large_thread-devel %{_description}

This package contains library source intended for building other packages which
use the "large_thread" feature of the "%{crate}" crate.

%files       -n rust-%{name}+large_thread-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+lint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+lint-devel %{_description}

This package contains library source intended for building other packages which
use the "lint" feature of the "%{crate}" crate.

%files       -n rust-%{name}+lint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+pretty-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+pretty-devel %{_description}

This package contains library source intended for building other packages which
use the "pretty" feature of the "%{crate}" crate.

%files       -n rust-%{name}+pretty-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+py_compat-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+py_compat-devel %{_description}

This package contains library source intended for building other packages which
use the "py_compat" feature of the "%{crate}" crate.

%files       -n rust-%{name}+py_compat-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+simplified_chinese-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+simplified_chinese-devel %{_description}

This package contains library source intended for building other packages which
use the "simplified_chinese" feature of the "%{crate}" crate.

%files       -n rust-%{name}+simplified_chinese-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+traditional_chinese-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+traditional_chinese-devel %{_description}

This package contains library source intended for building other packages which
use the "traditional_chinese" feature of the "%{crate}" crate.

%files       -n rust-%{name}+traditional_chinese-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n rust-%{name}+unicode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n rust-%{name}+unicode-devel %{_description}

This package contains library source intended for building other packages which
use the "unicode" feature of the "%{crate}" crate.

%files       -n rust-%{name}+unicode-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
## why this twos stucks?
%cargo_test -- -- --skip test_open --skip test_dependents_check
%endif

%changelog
%autochangelog
