# Generated by go2rpm 1.17.1
%bcond check 1

# https://github.com/fcying/compiledb-go
%global goipath         github.com/fcying/compiledb-go
Version:                1.5.2

%gometa -L -f


Name:           golang-github-fcying-compiledb
Release:        %autorelease
Summary:        Tool for generating Clang's JSON Compilation Database files for make-based build systems

# Generated by go-vendor-tools
License:        BSD-2-Clause AND BSD-3-Clause AND GPL-3.0-only AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

Patch0:         fix-test.patch

BuildRequires:  go-vendor-tools

Conflicts:      rust-compiledb
Conflicts:      python-compiledb

%description
Tool for generating Clang's JSON Compilation Database files for make-based
build systems.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%{_bindir}/compiledb


%changelog
%autochangelog
