# Generated by rust2rpm 27
# * Disable tests because of missing test data (excluded in Cargo.toml by
#   upstream)
%bcond check 0
%global debug_package %{nil}

%global crate i18n-embed-fl

Name:           rust-i18n-embed-fl
Version:        0.9.4
Release:        %autorelease
Summary:        Macro to perform compile time checks when using the i18n-embed crate and the fluent localization system

License:        MIT
URL:            https://crates.io/crates/i18n-embed-fl
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Macro to perform compile time checks when using the i18n-embed crate and
the fluent localization system.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dashmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dashmap-devel %{_description}

This package contains library source intended for building other packages which
use the "dashmap" feature of the "%{crate}" crate.

%files       -n %{name}+dashmap-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
