# Generated by rust2rpm 28
# * tests depend on aws_lc_rs which is dropped in Fedora's rustls package
%bcond check 0
%global debug_package %{nil}

%global crate hudsucker

Name:           rust-hudsucker
Version:        0.24.1
Release:        %autorelease
Summary:        MITM HTTP/S proxy

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/hudsucker
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli

%global _description %{expand:
MITM HTTP/S proxy.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+decoder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+decoder-devel %{_description}

This package contains library source intended for building other packages which
use the "decoder" feature of the "%{crate}" crate.

%files       -n %{name}+decoder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-devel %{_description}

This package contains library source intended for building other packages which
use the "full" feature of the "%{crate}" crate.

%files       -n %{name}+full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http2-devel %{_description}

This package contains library source intended for building other packages which
use the "http2" feature of the "%{crate}" crate.

%files       -n %{name}+http2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-client-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-client-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls-client" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-client-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+openssl-ca-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-ca-devel %{_description}

This package contains library source intended for building other packages which
use the "openssl-ca" feature of the "%{crate}" crate.

%files       -n %{name}+openssl-ca-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rcgen-ca-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rcgen-ca-devel %{_description}

This package contains library source intended for building other packages which
use the "rcgen-ca" feature of the "%{crate}" crate.

%files       -n %{name}+rcgen-ca-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-client-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-client-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-client" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-client-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
# Remove dev dependencie
tomcli-set Cargo.toml del dev-dependencies.criterion
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
