# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate async-http-proxy

Name:           rust-async-http-proxy
Version:        1.2.5
Release:        %autorelease
Summary:        Lightweight asynchronous HTTP proxy client library

License:        BSD-3-Clause
URL:            https://crates.io/crates/async-http-proxy
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          async-http-proxy-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Lightweight asynchronous HTTP proxy client library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "async-std" feature of the "%{crate}" crate.

%files       -n %{name}+async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+base64-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+base64-devel %{_description}

This package contains library source intended for building other packages which
use the "base64" feature of the "%{crate}" crate.

%files       -n %{name}+base64-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+basic-auth-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+basic-auth-devel %{_description}

This package contains library source intended for building other packages which
use the "basic-auth" feature of the "%{crate}" crate.

%files       -n %{name}+basic-auth-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-async-std" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
