# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate libyml

Name:           rust-libyml
Version:        0.0.5
Release:        %autorelease
Summary:        Safe and efficient Rust library for parsing, emitting, and manipulating YAML data

License:        MIT
URL:            https://crates.io/crates/libyml
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * remove unused bin and remove failed tests due to dependecies is path based
Patch:          libyml-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A safe and efficient Rust library for parsing, emitting, and
manipulating YAML data.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+test-utils-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+test-utils-devel %{_description}

This package contains library source intended for building other packages which
use the "test-utils" feature of the "%{crate}" crate.

%files       -n %{name}+test-utils-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
