# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate range-collections

Name:           rust-range-collections
Version:        0.4.6
Release:        %autorelease
Summary:        Sets and maps of ranges, backed by smallvec

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/range-collections
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          range-collections-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Sets and maps of ranges, backed by smallvec.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE2.md
%license %{crate_instdir}/LICENSE-MIT.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytecheck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytecheck-devel %{_description}

This package contains library source intended for building other packages which
use the "bytecheck" feature of the "%{crate}" crate.

%files       -n %{name}+bytecheck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+new_unchecked-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+new_unchecked-devel %{_description}

This package contains library source intended for building other packages which
use the "new_unchecked" feature of the "%{crate}" crate.

%files       -n %{name}+new_unchecked-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv_validated-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv_validated-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv_validated" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv_validated-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
