specfile_path: golang-github-spf13-viper.spec

upstream_package_name: viper
upstream_project_url: https://github.com/spf13/viper
downstream_package_name: golang-github-spf13-viper

upstream_tag_template: v{version}

jobs:

- job: pull_from_upstream
  trigger: release
  dist_git_branches:
   - fedora-rawhide

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-rawhide
