# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate rmux-proto

Name:           rust-rmux-proto
Version:        0.3.1
Release:        %autorelease
Summary:        RMUX detached IPC protocol DTOs, framing, and wire-safe error types

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/rmux-proto
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  tomcli

%global _description %{expand:
RMUX detached IPC protocol DTOs, framing, and wire-safe error types.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
# Drop tests that require files which are not included in published crates to build
tomcli-set Cargo.toml arrays delitem test --key name 'wire_compat'
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip tests that require files which are not included in published crates to
#   run
%{cargo_test -- -- --exact %{shrink:
    --skip every_ledger_some_fixture_has_corresponding_file_on_disk
    --skip every_v1_fixture_file_on_disk_has_a_ledger_entry
    --skip fixture_bytes_match_canonical_encoding
    --skip fixture_envelope_payload_length_lies_within_default_max
    --skip fixture_envelope_uses_v1_baseline
    --skip fixture_full_frame_decodes_through_decode_frame
    --skip fixture_full_frame_decodes_through_frame_decoder_in_byte_pieces
    --skip fixture_full_frame_decodes_through_frame_decoder_in_one_shot
    --skip fixture_full_frame_decodes_through_frame_decoder_with_max_length_at_payload_size
    --skip fixture_payload_first_four_bytes_match_ledger_bincode_tag
    --skip fixture_round_trips_decode_then_re_encode_byte_for_byte
    --skip fixture_truncated_by_one_byte_is_rejected
    --skip fixture_with_trailing_byte_is_rejected_by_decode_frame
    --skip frame_decoder_clears_buffer_after_bad_magic_and_keeps_working
    --skip frame_decoder_handles_back_to_back_request_fixtures
    --skip frame_decoder_recovers_after_payload_decode_error
    --skip frame_decoder_rejects_corrupt_fixture_magic
    --skip frame_decoder_rejects_payload_exactly_one_byte_over_max
    --skip frame_decoder_rejects_unsupported_wire_version
    --skip frame_decoder_with_zero_byte_chunks_still_decodes
    --skip payload_only_bincode_roundtrip_supplements_full_frame_coverage
}}
%endif

%changelog
%autochangelog
