# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate grammers-client

Name:           rust-grammers-client
Version:        0.9.0
Release:        %autorelease
Summary:        High level client to interact with Telegram's API

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/grammers-client
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          grammers-client-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A high level client to interact with Telegram's API.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/DEPS.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fs-devel %{_description}

This package contains library source intended for building other packages which
use the "fs" feature of the "%{crate}" crate.

%files       -n %{name}+fs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+html-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+html-devel %{_description}

This package contains library source intended for building other packages which
use the "html" feature of the "%{crate}" crate.

%files       -n %{name}+html-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+html5ever-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+html5ever-devel %{_description}

This package contains library source intended for building other packages which
use the "html5ever" feature of the "%{crate}" crate.

%files       -n %{name}+html5ever-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+markdown-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+markdown-devel %{_description}

This package contains library source intended for building other packages which
use the "markdown" feature of the "%{crate}" crate.

%files       -n %{name}+markdown-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parse_invite_link-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parse_invite_link-devel %{_description}

This package contains library source intended for building other packages which
use the "parse_invite_link" feature of the "%{crate}" crate.

%files       -n %{name}+parse_invite_link-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+proxy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+proxy-devel %{_description}

This package contains library source intended for building other packages which
use the "proxy" feature of the "%{crate}" crate.

%files       -n %{name}+proxy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pulldown-cmark-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pulldown-cmark-devel %{_description}

This package contains library source intended for building other packages which
use the "pulldown-cmark" feature of the "%{crate}" crate.

%files       -n %{name}+pulldown-cmark-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+url-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+url-devel %{_description}

This package contains library source intended for building other packages which
use the "url" feature of the "%{crate}" crate.

%files       -n %{name}+url-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
