# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate pathfinding

Name:           rust-pathfinding
Version:        3.0.14
Release:        %autorelease
Summary:        Pathfinding, flow, and graph algorithms

# Upstream license specification: Apache-2.0/MIT
License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/pathfinding
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          pathfinding-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Pathfinding, flow, and graph algorithms.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
## output of tests/ui/matrix.rs slightly different in different rust version
## Ref: https://github.com/evenfurther/pathfinding/commit/2024b1621b5b7878497c8a098164ee5527953d85
%cargo_test -- -- --skip ui
%endif

%changelog
%autochangelog
