# Generated by rust2rpm 27
# * Disable tests because of missing test data (excluded in Cargo.toml by
#   upstream)
%bcond check 0
%global debug_package %{nil}

%global crate docx-rs

Name:           rust-docx-rs
Version:        0.4.18
Release:        %autorelease
Summary:        .docx file writer with Rust/WebAssembly

License:        MIT
URL:            https://crates.io/crates/docx-rs
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A .docx file writer with Rust/WebAssembly.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-devel %{_description}

This package contains library source intended for building other packages which
use the "image" feature of the "%{crate}" crate.

%files       -n %{name}+image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ts-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ts-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "ts-rs" feature of the "%{crate}" crate.

%files       -n %{name}+ts-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm" feature of the "%{crate}" crate.

%files       -n %{name}+wasm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasm-bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm-bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm-bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+wasm-bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
