# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate apk-info-axml

Name:           rust-apk-info-axml
Version:        1.0.11
Release:        %autorelease
Summary:        Library for working with AXML and ARSC in APK files

License:        Apache-2.0
URL:            https://crates.io/crates/apk-info-axml
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          apk-info-axml-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for working with AXML and ARSC in APK files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+converter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+converter-devel %{_description}

This package contains library source intended for building other packages which
use the "converter" feature of the "%{crate}" crate.

%files       -n %{name}+converter-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
