# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate wholesym

Name:           rust-wholesym
Version:        0.8.1
Release:        %autorelease
Summary:        Complete solution for fetching symbol files and resolving code addresses to symbols and debuginfo

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/wholesym
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          wholesym-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
Patch:          wholesym-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A complete solution for fetching symbol files and resolving code
addresses to symbols and debuginfo.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+api-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+api-devel %{_description}

This package contains library source intended for building other packages which
use the "api" feature of the "%{crate}" crate.

%files       -n %{name}+api-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+samply-api-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+samply-api-devel %{_description}

This package contains library source intended for building other packages which
use the "samply-api" feature of the "%{crate}" crate.

%files       -n %{name}+samply-api-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
