# Generated by rust2rpm 27
# * construct dependency fast
%bcond check 0
%global debug_package %{nil}

%global crate fluent-uri

Name:           rust-fluent-uri
Version:        0.1.4
Release:        %autorelease
Summary:        Generic URI parser that strictly adheres to IETF RFC 3986

License:        MIT
URL:            https://crates.io/crates/fluent-uri
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A generic URI parser that strictly adheres to IETF RFC 3986.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ipv_future-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ipv_future-devel %{_description}

This package contains library source intended for building other packages which
use the "ipv_future" feature of the "%{crate}" crate.

%files       -n %{name}+ipv_future-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rfc6874bis-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rfc6874bis-devel %{_description}

This package contains library source intended for building other packages which
use the "rfc6874bis" feature of the "%{crate}" crate.

%files       -n %{name}+rfc6874bis-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
