# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate framehop

Name:           rust-framehop
Version:        0.15.0
Release:        %autorelease
Summary:        Stack frame unwinding support for various formats

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/framehop
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Stack frame unwinding support for various formats.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/Readme.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+macho-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macho-devel %{_description}

This package contains library source intended for building other packages which
use the "macho" feature of the "%{crate}" crate.

%files       -n %{name}+macho-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+macho-unwind-info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macho-unwind-info-devel %{_description}

This package contains library source intended for building other packages which
use the "macho-unwind-info" feature of the "%{crate}" crate.

%files       -n %{name}+macho-unwind-info-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pe-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pe-devel %{_description}

This package contains library source intended for building other packages which
use the "pe" feature of the "%{crate}" crate.

%files       -n %{name}+pe-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pe-unwind-info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pe-unwind-info-devel %{_description}

This package contains library source intended for building other packages which
use the "pe-unwind-info" feature of the "%{crate}" crate.

%files       -n %{name}+pe-unwind-info-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
