# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate watchman_client

Name:           rust-watchman_client
Version:        0.9.0
Release:        %autorelease
Summary:        Client for the Watchman file watching service

License:        MIT
URL:            https://crates.io/crates/watchman_client
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          watchman_client-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
Patch:          watchman_client-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A client for the Watchman file watching service.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
