# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate yaxpeax-arch

Name:           rust-yaxpeax-arch
Version:        0.3.2
Release:        %autorelease
Summary:        Fundamental traits to describe an architecture in the yaxpeax project

License:        0BSD
URL:            https://crates.io/crates/yaxpeax-arch
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fundamental traits to describe an architecture in the yaxpeax project.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+address-parse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+address-parse-devel %{_description}

This package contains library source intended for building other packages which
use the "address-parse" feature of the "%{crate}" crate.

%files       -n %{name}+address-parse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+color-new-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+color-new-devel %{_description}

This package contains library source intended for building other packages which
use the "color-new" feature of the "%{crate}" crate.

%files       -n %{name}+color-new-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+colors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+colors-devel %{_description}

This package contains library source intended for building other packages which
use the "colors" feature of the "%{crate}" crate.

%files       -n %{name}+colors-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+crossterm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crossterm-devel %{_description}

This package contains library source intended for building other packages which
use the "crossterm" feature of the "%{crate}" crate.

%files       -n %{name}+crossterm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_derive-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_derive" feature of the "%{crate}" crate.

%files       -n %{name}+serde_derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+use-serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use-serde-devel %{_description}

This package contains library source intended for building other packages which
use the "use-serde" feature of the "%{crate}" crate.

%files       -n %{name}+use-serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --skip instruction_text_sink_write_char_rejects_not_ascii
%endif

%changelog
%autochangelog
