# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate minidump-unwind

Name:           rust-minidump-unwind
Version:        0.26.1
Release:        %autorelease
Summary:        Library for producing stack traces from minidump files

License:        MIT
URL:            https://crates.io/crates/minidump-unwind
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library for producing stack traces from minidump files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cachemap2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cachemap2-devel %{_description}

This package contains library source intended for building other packages which
use the "cachemap2" feature of the "%{crate}" crate.

%files       -n %{name}+cachemap2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debuginfo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debuginfo-devel %{_description}

This package contains library source intended for building other packages which
use the "debuginfo" feature of the "%{crate}" crate.

%files       -n %{name}+debuginfo-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debuginfo-symbols-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debuginfo-symbols-devel %{_description}

This package contains library source intended for building other packages which
use the "debuginfo-symbols" feature of the "%{crate}" crate.

%files       -n %{name}+debuginfo-symbols-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debuginfo-unwind-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debuginfo-unwind-devel %{_description}

This package contains library source intended for building other packages which
use the "debuginfo-unwind" feature of the "%{crate}" crate.

%files       -n %{name}+debuginfo-unwind-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+framehop-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+framehop-devel %{_description}

This package contains library source intended for building other packages which
use the "framehop" feature of the "%{crate}" crate.

%files       -n %{name}+framehop-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-util-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-util" feature of the "%{crate}" crate.

%files       -n %{name}+futures-util-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http-devel %{_description}

This package contains library source intended for building other packages which
use the "http" feature of the "%{crate}" crate.

%files       -n %{name}+http-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+memmap2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+memmap2-devel %{_description}

This package contains library source intended for building other packages which
use the "memmap2" feature of the "%{crate}" crate.

%files       -n %{name}+memmap2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+object-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+object-devel %{_description}

This package contains library source intended for building other packages which
use the "object" feature of the "%{crate}" crate.

%files       -n %{name}+object-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wholesym-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wholesym-devel %{_description}

This package contains library source intended for building other packages which
use the "wholesym" feature of the "%{crate}" crate.

%files       -n %{name}+wholesym-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
