# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           mihomosh
Version:        2.0.0
Release:        %autorelease
Summary:        # FIXME

SourceLicense:  GPL-3.0-or-later
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/SamuNatsu/mihomosh
Source:         %{url}/archive/v%{version}/%{name}-v%{version}.tar.gz
# Manually created patch for downstream crate metadata changes
Patch:          mihomosh-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 26

## todo generate shell completion with `mihomosh shell-completion bash/zsh/fish` after built
Recommends:     clash-meta

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n %{name}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README-zh_cn.md
%doc README.md
%{_bindir}/mihomosh

%changelog
%autochangelog
