# Generated by rust2rpm 27
%bcond check 1

%global crate rage

Name:           rust-rage
Version:        0.11.1
Release:        %autorelease
Summary:        [BETA] A simple, secure, and modern encryption tool

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/rage
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          rage-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(fuse3)

%global _description %{expand:
[BETA] A simple, secure, and modern encryption tool.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/rage
%{_bindir}/rage-keygen
%{_bindir}/rage-mount

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f mount

%build
%cargo_build -f mount
%{cargo_license_summary -f mount}
%{cargo_license -f mount} > LICENSE.dependencies

%install
%cargo_install -f mount

%if %{with check}
%check
%cargo_test -f mount
%endif

%changelog
%autochangelog
